

#include "gambit\header\variables.inc"
#include "gambit\header\anim.inc"
#include "gambit\header\death.inc"
#include "gambit\header\pin.inc"
#include "gambit\header\frac.inc"
#include "gambit\header\vehicle.inc"
#include "gambit\header\tuning.inc"
#include "gambit\header\graffiti.inc"
#include "gambit\header\enters.inc"
#include "gambit\header\house.inc"

#include "gambit\header\crime.inc"
#include "gambit\header\job.inc"
#include "gambit\header\atm.inc"

#include "gambit\header\prison.inc"

#include "gambit\header\admin.inc"