
#include "gambit\connection.pwn"

#include "gambit\script\anticheat\avtp.pwn"

#include "gambit\object.pwn"
#include "gambit\date.pwn"
#include "gambit\functions.pwn"
#include "gambit\script\proxd.pwn"

#include "gambit\script\anticheat.pwn"
#include "gambit\script\enters.pwn"

#include "gambit\script\inventory\inv_td.pwn"

#include "gambit\script\house\hostel.pwn"
#include "gambit\script\house\house_furniture.pwn"
#include "gambit\script\house\house_core.pwn"
#include "gambit\script\house\house_enter.pwn"
#include "gambit\script\house\house_buy.pwn"
#include "gambit\script\house\house_panel.pwn"
#include "gambit\script\house\house_inv.pwn"
#include "gambit\script\house\house_test.pwn"
#include "gambit\script\house\house_interior.pwn"
#include "gambit\script\house\house_texture.pwn"
#include "gambit\script\house\house_create.pwn"

#include "gambit\script\spawn.pwn"
#include "gambit\script\login.pwn"
#include "gambit\script\death.pwn"

#include "gambit\script\pin.pwn"
#include "gambit\script\anim.pwn"
#include "gambit\script\gps.pwn"

#include "gambit\script\lspd\garage_lspd.pwn"
#include "gambit\script\lspd\lspd_sasd.pwn"
#include "gambit\script\lspd\lspd_cmd.pwn"

#include "gambit\script\cnn.pwn"

#include "gambit\script\fd\fd_attach.pwn"

#include "gambit\script\graffiti.pwn"
#include "gambit\script\help.pwn"

#include "gambit\script\vehicle\tuning.pwn"

#include "gambit\script\criminal\crime.pwn"
#include "gambit\script\criminal\crime_veh.pwn"
#include "gambit\script\criminal\crime_create.pwn"
#include "gambit\script\criminal\crime_cmd.pwn"


#include "gambit\script\job\bus.pwn"
#include "gambit\script\job\taxi.pwn"

#include "gambit\script\prison\prison_interior.pwn"
#include "gambit\script\prison\prison_exterior.pwn"

#include "gambit\script\prison\prison.pwn"
#include "gambit\script\prison\prison_gate.pwn"
#include "gambit\script\prison\prison_teleport.pwn"
#include "gambit\script\prison\prison_cgate.pwn"
#include "gambit\script\prison\prison_cctv.pwn"
#include "gambit\script\prison\prison_panel.pwn"
#include "gambit\script\prison\prison_veh.pwn"
//#include "gambit\script\prison\prison_actor.pwn"
#include "gambit\script\prison\prison_arrest.pwn"

#include "gambit\script\admin\admin_menu.pwn"
#include "gambit\script\admin\admin_cmd.pwn"
#include "gambit\script\admin\admin_func.pwn"
#include "gambit\script\admin\admin_dialog.pwn"

#include "gambit\script\user_menu.pwn"
#include "gambit\script\atm.pwn"
#include "gambit\script\pattach.pwn"
#include "gambit\script\payday.pwn"
#include "gambit\script\weather.pwn"
#include "gambit\script\logs.pwn"