// -- Подарки
#define GIFT_SMALL					( 27 )
#define GIFT_MEDIUM					( 28 )
#define GIFT_BIG					( 29 )
#define GIFT_JOB					( 165 )

// -- Купоны
#define COUPON_LICENSES				( 94 )
#define COUPON_CHANGE_NAME			( 102 )
#define COUPON_CHANGE_ROLE			( 99 )
#define COUPON_CHANGE_AGE			( 98 )
#define COUPON_CHANGE_NUMBER		( 149 )
#define COUPON_CHANGE_CAR_NUMBER	( 150 )
#define COUPON_STYLE_FIGHTS			( 151 )
#define COUPON_JOB_POINTS			( 92 )
#define COUPON_UNWARNS				( 100 )
#define COUPON_UP_MASS				( 95 )

#define COUPON_DOUBLE_TAXI			( 30 )
#define COUPON_DOUBLE_BUS			( 31 )
#define COUPON_DOUBLE_VEHCOMPANY 	( 32 )
#define COUPON_DOUBLE_WOOD			( 34 )

// -- Премиум аккаунты
#define PREMIUM_LIGHT				( 159 )
#define PREMIUM_MEDIUM				( 160 )
#define PREMIUM_HARD				( 161 )
#define PREMIUM_PLATINUM			( 164 )

// -- 
#define JOB_TAXI					( 0 )
#define JOB_BUS						( 1 )
#define JOB_VEHCOMPANY				( 2 )
#define JOB_WOOD					( 4 )

#define UP_MASS						( 6 )