    Speed[0][playerid] = CreatePlayerTextDraw(playerid,281.000000, 403.000000, "ENG");PlayerTextDrawAlignment(playerid,Speed[0][playerid], 2);PlayerTextDrawBackgroundColor(playerid,Speed[0][playerid], 255);PlayerTextDrawFont(playerid,Speed[0][playerid], 2);
    PlayerTextDrawLetterSize(playerid,Speed[0][playerid], 0.180000, 1.000000);PlayerTextDrawColor(playerid,Speed[0][playerid], 255);PlayerTextDrawSetOutline(playerid,Speed[0][playerid], 0);PlayerTextDrawSetProportional(playerid,Speed[0][playerid], 1);
    PlayerTextDrawSetShadow(playerid,Speed[0][playerid], 0);PlayerTextDrawUseBox(playerid,Speed[0][playerid], 1);PlayerTextDrawBoxColor(playerid,Speed[0][playerid], 1438569552);PlayerTextDrawTextSize(playerid,Speed[0][playerid], 260.000000, -22.000000);PlayerTextDrawSetSelectable(playerid,Speed[0][playerid], 0);
    Speed[1][playerid] = CreatePlayerTextDraw(playerid,281.000000, 420.000000, "LIM");PlayerTextDrawAlignment(playerid,Speed[1][playerid], 2);PlayerTextDrawBackgroundColor(playerid,Speed[1][playerid], 255);PlayerTextDrawFont(playerid,Speed[1][playerid], 2);
    PlayerTextDrawLetterSize(playerid,Speed[1][playerid], 0.180000, 1.000000);PlayerTextDrawColor(playerid,Speed[1][playerid], 255);PlayerTextDrawSetOutline(playerid,Speed[1][playerid], 0);PlayerTextDrawSetProportional(playerid,Speed[1][playerid], 1);PlayerTextDrawSetShadow(playerid,Speed[1][playerid], 0);
    PlayerTextDrawUseBox(playerid,Speed[1][playerid], 1);PlayerTextDrawBoxColor(playerid,Speed[1][playerid], 1438569552);PlayerTextDrawTextSize(playerid,Speed[1][playerid], 260.000000, -22.000000);PlayerTextDrawSetSelectable(playerid,Speed[1][playerid], 0);
    Speed[2][playerid] = CreatePlayerTextDraw(playerid,370.500000, 403.000000, "LAMP");PlayerTextDrawAlignment(playerid,Speed[2][playerid], 2);PlayerTextDrawBackgroundColor(playerid,Speed[2][playerid], 255);PlayerTextDrawFont(playerid,Speed[2][playerid], 2);
    PlayerTextDrawLetterSize(playerid,Speed[2][playerid], 0.140000, 1.000000);PlayerTextDrawColor(playerid,Speed[2][playerid], 255);PlayerTextDrawSetOutline(playerid,Speed[2][playerid], 0);PlayerTextDrawSetProportional(playerid,Speed[2][playerid], 1);
    PlayerTextDrawSetShadow(playerid,Speed[2][playerid], 0);PlayerTextDrawUseBox(playerid,Speed[2][playerid], 1);PlayerTextDrawBoxColor(playerid,Speed[2][playerid], 1438569552);PlayerTextDrawTextSize(playerid,Speed[2][playerid], 260.000000, -22.000000);PlayerTextDrawSetSelectable(playerid,Speed[2][playerid], 0);
    Speed[3][playerid] = CreatePlayerTextDraw(playerid,370.500000, 420.000000, "lock");PlayerTextDrawAlignment(playerid,Speed[3][playerid], 2);PlayerTextDrawBackgroundColor(playerid,Speed[3][playerid], 255);
    PlayerTextDrawFont(playerid,Speed[3][playerid], 2);PlayerTextDrawLetterSize(playerid,Speed[3][playerid], 0.140000, 1.000000);PlayerTextDrawColor(playerid,Speed[3][playerid], 255);PlayerTextDrawSetOutline(playerid,Speed[3][playerid], 0);
    PlayerTextDrawSetProportional(playerid,Speed[3][playerid], 1);PlayerTextDrawSetShadow(playerid,Speed[3][playerid], 0);PlayerTextDrawUseBox(playerid,Speed[3][playerid], 1);PlayerTextDrawBoxColor(playerid,Speed[3][playerid], 1438569552);PlayerTextDrawTextSize(playerid,Speed[3][playerid], 260.000000, -22.000000);
	PlayerTextDrawSetSelectable(playerid,Speed[3][playerid], 0);
    Speed[4][playerid] = CreatePlayerTextDraw(playerid,327.000000, 415.000000, "0 mp");PlayerTextDrawAlignment(playerid,Speed[4][playerid], 2);PlayerTextDrawBackgroundColor(playerid,Speed[4][playerid], 255);PlayerTextDrawFont(playerid,Speed[4][playerid], 2);PlayerTextDrawLetterSize(playerid,Speed[4][playerid], 0.219999, 1.000000);
    PlayerTextDrawColor(playerid,Speed[4][playerid], -176);PlayerTextDrawSetOutline(playerid,Speed[4][playerid], 0);PlayerTextDrawSetProportional(playerid,Speed[4][playerid], 1);PlayerTextDrawSetShadow(playerid,Speed[4][playerid], 0);PlayerTextDrawSetSelectable(playerid,Speed[4][playerid], 0);
    Speed[5][playerid] = CreatePlayerTextDraw(playerid,327.000000, 397.000000, "0 mp/h");PlayerTextDrawAlignment(playerid,Speed[5][playerid], 2);PlayerTextDrawBackgroundColor(playerid,Speed[5][playerid], 255);PlayerTextDrawFont(playerid,Speed[5][playerid], 2);PlayerTextDrawLetterSize(playerid,Speed[5][playerid], 0.270000, 2.099999);
    PlayerTextDrawColor(playerid,Speed[5][playerid], -176);PlayerTextDrawSetOutline(playerid,Speed[5][playerid], 0);PlayerTextDrawSetProportional(playerid,Speed[5][playerid], 1);PlayerTextDrawSetShadow(playerid,Speed[5][playerid], 0);PlayerTextDrawSetSelectable(playerid,Speed[5][playerid], 0);
    Speed[6][playerid] = CreatePlayerTextDraw(playerid,272.500000, 380.000000, "IIIIIII");PlayerTextDrawBackgroundColor(playerid,Speed[6][playerid], 255);PlayerTextDrawFont(playerid,Speed[6][playerid], 2);PlayerTextDrawLetterSize(playerid,Speed[6][playerid], 0.500000, 2.200000);PlayerTextDrawColor(playerid,Speed[6][playerid], -176);
    PlayerTextDrawSetOutline(playerid,Speed[6][playerid], 0);PlayerTextDrawSetProportional(playerid,Speed[6][playerid], 1);PlayerTextDrawSetShadow(playerid,Speed[6][playerid], 0);PlayerTextDrawSetSelectable(playerid,Speed[6][playerid], 0);
	
	Speed[7][playerid] = CreatePlayerTextDraw(playerid,295.000000, 428.000000, "_");PlayerTextDrawBackgroundColor(playerid,Speed[7][playerid], 255);PlayerTextDrawFont(playerid,Speed[7][playerid], 1);PlayerTextDrawLetterSize(playerid,Speed[7][playerid], 0.500000, 0.099999);
	PlayerTextDrawColor(playerid,Speed[7][playerid], -1);PlayerTextDrawSetOutline(playerid,Speed[7][playerid], 0);PlayerTextDrawSetProportional(playerid,Speed[7][playerid], 1);PlayerTextDrawSetShadow(playerid,Speed[7][playerid], 1);
	PlayerTextDrawUseBox(playerid,Speed[7][playerid], 1);PlayerTextDrawBoxColor(playerid,Speed[7][playerid], -176);PlayerTextDrawTextSize(playerid,Speed[7][playerid], 357.000000, 0.000000);PlayerTextDrawSetSelectable(playerid,Speed[7][playerid], 0);
	
	FermSelectSkin[0][playerid] = CreatePlayerTextDraw(playerid,206.000000, 201.000000, "skinselect");PlayerTextDrawBackgroundColor(playerid,FermSelectSkin[0][playerid], -707406934);PlayerTextDrawFont(playerid,FermSelectSkin[0][playerid], 5);
	PlayerTextDrawLetterSize(playerid,FermSelectSkin[0][playerid], 0.500000, 3.699999);PlayerTextDrawColor(playerid,FermSelectSkin[0][playerid], -1);PlayerTextDrawSetOutline(playerid,FermSelectSkin[0][playerid], 0);PlayerTextDrawSetProportional(playerid,FermSelectSkin[0][playerid], 1);
	PlayerTextDrawSetShadow(playerid,FermSelectSkin[0][playerid], 1);PlayerTextDrawUseBox(playerid,FermSelectSkin[0][playerid], 1);PlayerTextDrawBoxColor(playerid,FermSelectSkin[0][playerid], 0);PlayerTextDrawTextSize(playerid,FermSelectSkin[0][playerid], 73.000000, 88.000000);PlayerTextDrawSetSelectable(playerid,FermSelectSkin[0][playerid], 1);
	FermSelectSkin[1][playerid] = CreatePlayerTextDraw(playerid,282.100006, 201.000000, "skinselect");PlayerTextDrawBackgroundColor(playerid,FermSelectSkin[1][playerid], -707406934);PlayerTextDrawFont(playerid,FermSelectSkin[1][playerid], 5);
	PlayerTextDrawLetterSize(playerid,FermSelectSkin[1][playerid], 0.500000, 3.699999);PlayerTextDrawColor(playerid,FermSelectSkin[1][playerid], -1);PlayerTextDrawSetOutline(playerid,FermSelectSkin[1][playerid], 0);PlayerTextDrawSetProportional(playerid,FermSelectSkin[1][playerid], 1);
	PlayerTextDrawSetShadow(playerid,FermSelectSkin[1][playerid], 1);PlayerTextDrawUseBox(playerid,FermSelectSkin[1][playerid], 1);PlayerTextDrawBoxColor(playerid,FermSelectSkin[1][playerid], 0);PlayerTextDrawTextSize(playerid,FermSelectSkin[1][playerid], 73.000000, 88.000000);PlayerTextDrawSetSelectable(playerid,FermSelectSkin[1][playerid], 1);
	FermSelectSkin[2][playerid] = CreatePlayerTextDraw(playerid,358.000000, 201.000000, "skinselect");PlayerTextDrawBackgroundColor(playerid,FermSelectSkin[2][playerid], -707406934);PlayerTextDrawFont(playerid,FermSelectSkin[2][playerid], 5);
	PlayerTextDrawLetterSize(playerid,FermSelectSkin[2][playerid], 0.500000, 3.699999);PlayerTextDrawColor(playerid,FermSelectSkin[2][playerid], -1);PlayerTextDrawSetOutline(playerid,FermSelectSkin[2][playerid], 0);PlayerTextDrawSetProportional(playerid,FermSelectSkin[2][playerid], 1);
	PlayerTextDrawSetShadow(playerid,FermSelectSkin[2][playerid], 1);PlayerTextDrawUseBox(playerid,FermSelectSkin[2][playerid], 1);PlayerTextDrawBoxColor(playerid,FermSelectSkin[2][playerid], 0);PlayerTextDrawTextSize(playerid,FermSelectSkin[2][playerid], 73.000000, 88.000000);PlayerTextDrawSetSelectable(playerid,FermSelectSkin[2][playerid], 1);
	
	NewSkinSelect[0][playerid] = CreatePlayerTextDraw(playerid, 139.000000, 146.429595, "PreviewModel");
	PlayerTextDrawLetterSize(playerid,NewSkinSelect[0][playerid], 0.095666, 3.364151);
	PlayerTextDrawTextSize(playerid,NewSkinSelect[0][playerid], 61.666648, 69.274085);
	PlayerTextDrawAlignment(playerid,NewSkinSelect[0][playerid], 1);
	PlayerTextDrawColor(playerid,NewSkinSelect[0][playerid], -1);
	PlayerTextDrawSetShadow(playerid,NewSkinSelect[0][playerid], 0);
	PlayerTextDrawSetOutline(playerid,NewSkinSelect[0][playerid], 0);
	PlayerTextDrawBackgroundColor(playerid,NewSkinSelect[0][playerid], -707406934);
	PlayerTextDrawFont(playerid,NewSkinSelect[0][playerid], 5);
	PlayerTextDrawSetPreviewModel(playerid,NewSkinSelect[0][playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid,NewSkinSelect[0][playerid], 0.000000, 0.000000, 0.000000, 1.000000);
	PlayerTextDrawSetSelectable(playerid,NewSkinSelect[0][playerid], true);

	NewSkinSelect[1][playerid] = CreatePlayerTextDraw(playerid, 203.666671, 146.600006, "PreviewModel");
	PlayerTextDrawLetterSize(playerid,NewSkinSelect[1][playerid], 0.060333, 0.647111);
	PlayerTextDrawTextSize(playerid,NewSkinSelect[1][playerid], 61.666648, 69.274085);
	PlayerTextDrawAlignment(playerid,NewSkinSelect[1][playerid], 1);
	PlayerTextDrawColor(playerid,NewSkinSelect[1][playerid], -1);
	PlayerTextDrawSetShadow(playerid,NewSkinSelect[1][playerid], 0);
	PlayerTextDrawSetOutline(playerid,NewSkinSelect[1][playerid], 0);
	PlayerTextDrawBackgroundColor(playerid,NewSkinSelect[1][playerid], -707406934);
	PlayerTextDrawFont(playerid,NewSkinSelect[1][playerid], 5);
	PlayerTextDrawSetPreviewModel(playerid,NewSkinSelect[1][playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid,NewSkinSelect[1][playerid], 0.000000, 0.000000, 0.000000, 1.000000);
	PlayerTextDrawSetSelectable(playerid,NewSkinSelect[1][playerid], true);

	NewSkinSelect[2][playerid] = CreatePlayerTextDraw(playerid, 268.666473, 146.770355, "PreviewModel");
	PlayerTextDrawLetterSize(playerid,NewSkinSelect[2][playerid], 0.060666, 0.672000);
	PlayerTextDrawTextSize(playerid,NewSkinSelect[2][playerid], 61.666648, 69.274085);
	PlayerTextDrawAlignment(playerid,NewSkinSelect[2][playerid], 1);
	PlayerTextDrawColor(playerid,NewSkinSelect[2][playerid], -1);
	PlayerTextDrawSetShadow(playerid,NewSkinSelect[2][playerid], 0);
	PlayerTextDrawSetOutline(playerid,NewSkinSelect[2][playerid], 0);
	PlayerTextDrawBackgroundColor(playerid,NewSkinSelect[2][playerid], -707406934);
	PlayerTextDrawFont(playerid,NewSkinSelect[2][playerid], 5);
	PlayerTextDrawSetPreviewModel(playerid,NewSkinSelect[2][playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid,NewSkinSelect[2][playerid], 0.000000, 0.000000, 0.000000, 1.000000);
	PlayerTextDrawSetSelectable(playerid,NewSkinSelect[2][playerid], true);

	NewSkinSelect[3][playerid] = CreatePlayerTextDraw(playerid,332.999816, 146.940734, "PreviewModel");
	PlayerTextDrawLetterSize(playerid,NewSkinSelect[3][playerid], 0.059333, 0.684444);
	PlayerTextDrawTextSize(playerid,NewSkinSelect[3][playerid], 61.666648, 69.274085);
	PlayerTextDrawAlignment(playerid,NewSkinSelect[3][playerid], 1);
	PlayerTextDrawColor(playerid,NewSkinSelect[3][playerid], -1);
	PlayerTextDrawSetShadow(playerid,NewSkinSelect[3][playerid], 0);
	PlayerTextDrawSetOutline(playerid,NewSkinSelect[3][playerid], 0);
	PlayerTextDrawBackgroundColor(playerid,NewSkinSelect[3][playerid], -707406934);
	PlayerTextDrawFont(playerid,NewSkinSelect[3][playerid], 5);
	PlayerTextDrawSetPreviewModel(playerid,NewSkinSelect[3][playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid,NewSkinSelect[3][playerid], 0.000000, 0.000000, 0.000000, 1.000000);
	PlayerTextDrawSetSelectable(playerid,NewSkinSelect[3][playerid], true);

	NewSkinSelect[4][playerid] = CreatePlayerTextDraw(playerid,397.333129, 146.696365, "PreviewModel");
	PlayerTextDrawLetterSize(playerid,NewSkinSelect[4][playerid], 0.123999, 0.754962);
	PlayerTextDrawTextSize(playerid,NewSkinSelect[4][playerid], 61.666648, 69.274085);
	PlayerTextDrawAlignment(playerid,NewSkinSelect[4][playerid], 1);
	PlayerTextDrawColor(playerid,NewSkinSelect[4][playerid], -1);
	PlayerTextDrawSetShadow(playerid,NewSkinSelect[4][playerid], 0);
	PlayerTextDrawSetOutline(playerid,NewSkinSelect[4][playerid], 0);
	PlayerTextDrawBackgroundColor(playerid,NewSkinSelect[4][playerid], -707406934);
	PlayerTextDrawFont(playerid,NewSkinSelect[4][playerid], 5);
	PlayerTextDrawSetPreviewModel(playerid,NewSkinSelect[4][playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid,NewSkinSelect[4][playerid], 0.000000, 0.000000, 0.000000, 1.000000);
	PlayerTextDrawSetSelectable(playerid,NewSkinSelect[4][playerid], true);

	NewSkinSelect[5][playerid] = CreatePlayerTextDraw(playerid,461.999725, 146.866729, "PreviewModel");
	PlayerTextDrawLetterSize(playerid,NewSkinSelect[5][playerid], 0.066999, 1.335703);
	PlayerTextDrawTextSize(playerid,NewSkinSelect[5][playerid], 61.666648, 69.274085);
	PlayerTextDrawAlignment(playerid,NewSkinSelect[5][playerid], 1);
	PlayerTextDrawColor(playerid,NewSkinSelect[5][playerid], -1);
	PlayerTextDrawSetShadow(playerid,NewSkinSelect[5][playerid], 0);
	PlayerTextDrawSetOutline(playerid,NewSkinSelect[5][playerid], 0);
	PlayerTextDrawBackgroundColor(playerid,NewSkinSelect[5][playerid], -707406934);
	PlayerTextDrawFont(playerid,NewSkinSelect[5][playerid], 5);
	PlayerTextDrawSetPreviewModel(playerid,NewSkinSelect[5][playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid,NewSkinSelect[5][playerid], 0.000000, 0.000000, 0.000000, 1.000000);
	PlayerTextDrawSetSelectable(playerid,NewSkinSelect[5][playerid], true);

	NewSkinSelect[6][playerid] = CreatePlayerTextDraw(playerid,139.000000, 221.681442, "PreviewModel");
	PlayerTextDrawLetterSize(playerid,NewSkinSelect[6][playerid], 0.155333, 4.048594);
	PlayerTextDrawTextSize(playerid,NewSkinSelect[6][playerid], 61.666648, 69.274085);
	PlayerTextDrawAlignment(playerid,NewSkinSelect[6][playerid], 1);
	PlayerTextDrawColor(playerid,NewSkinSelect[6][playerid], -1);
	PlayerTextDrawSetShadow(playerid,NewSkinSelect[6][playerid], 0);
	PlayerTextDrawSetOutline(playerid,NewSkinSelect[6][playerid], 0);
	PlayerTextDrawBackgroundColor(playerid,NewSkinSelect[6][playerid], -707406934);
	PlayerTextDrawFont(playerid,NewSkinSelect[6][playerid], 5);
	PlayerTextDrawSetPreviewModel(playerid,NewSkinSelect[6][playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid,NewSkinSelect[6][playerid], 0.000000, 0.000000, 0.000000, 1.000000);
	PlayerTextDrawSetSelectable(playerid,NewSkinSelect[6][playerid], true);

	NewSkinSelect[7][playerid] = CreatePlayerTextDraw(playerid,204.000045, 221.851806, "PreviewModel");
	PlayerTextDrawLetterSize(playerid,NewSkinSelect[7][playerid], 0.158666, 4.023706);
	PlayerTextDrawTextSize(playerid,NewSkinSelect[7][playerid], 61.666648, 69.274085);
	PlayerTextDrawAlignment(playerid,NewSkinSelect[7][playerid], 1);
	PlayerTextDrawColor(playerid,NewSkinSelect[7][playerid], -1);
	PlayerTextDrawSetShadow(playerid,NewSkinSelect[7][playerid], 0);
	PlayerTextDrawSetOutline(playerid,NewSkinSelect[7][playerid], 0);
	PlayerTextDrawBackgroundColor(playerid,NewSkinSelect[7][playerid], -707406934);
	PlayerTextDrawFont(playerid,NewSkinSelect[7][playerid], 5);
	PlayerTextDrawSetPreviewModel(playerid,NewSkinSelect[7][playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid,NewSkinSelect[7][playerid], 0.000000, 0.000000, 0.000000, 1.000000);
	PlayerTextDrawSetSelectable(playerid,NewSkinSelect[7][playerid], true);

	NewSkinSelect[8][playerid] = CreatePlayerTextDraw(playerid,269.333374, 221.607376, "PreviewModel");
	PlayerTextDrawLetterSize(playerid,NewSkinSelect[8][playerid], 0.158999, 4.011263);
	PlayerTextDrawTextSize(playerid,NewSkinSelect[8][playerid], 61.666648, 69.274085);
	PlayerTextDrawAlignment(playerid,NewSkinSelect[8][playerid], 1);
	PlayerTextDrawColor(playerid,NewSkinSelect[8][playerid], -1);
	PlayerTextDrawSetShadow(playerid,NewSkinSelect[8][playerid], 0);
	PlayerTextDrawSetOutline(playerid,NewSkinSelect[8][playerid], 0);
	PlayerTextDrawBackgroundColor(playerid,NewSkinSelect[8][playerid], -707406934);
	PlayerTextDrawFont(playerid,NewSkinSelect[8][playerid], 5);
	PlayerTextDrawSetPreviewModel(playerid,NewSkinSelect[8][playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid,NewSkinSelect[8][playerid], 0.000000, 0.000000, 0.000000, 1.000000);
	PlayerTextDrawSetSelectable(playerid,NewSkinSelect[8][playerid], true);

	NewSkinSelect[9][playerid] = CreatePlayerTextDraw(playerid,334.666625, 221.777725, "PreviewModel");
	PlayerTextDrawLetterSize(playerid,NewSkinSelect[9][playerid], 0.157999, 4.048594);
	PlayerTextDrawTextSize(playerid,NewSkinSelect[9][playerid], 61.666648, 69.274085);
	PlayerTextDrawAlignment(playerid,NewSkinSelect[9][playerid], 1);
	PlayerTextDrawColor(playerid,NewSkinSelect[9][playerid], -1);
	PlayerTextDrawSetShadow(playerid,NewSkinSelect[9][playerid], 0);
	PlayerTextDrawSetOutline(playerid,NewSkinSelect[9][playerid], 0);
	PlayerTextDrawBackgroundColor(playerid,NewSkinSelect[9][playerid], -707406934);
	PlayerTextDrawFont(playerid,NewSkinSelect[9][playerid], 5);
	PlayerTextDrawSetPreviewModel(playerid,NewSkinSelect[9][playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid,NewSkinSelect[9][playerid], 0.000000, 0.000000, 0.000000, 1.000000);
	PlayerTextDrawSetSelectable(playerid,NewSkinSelect[9][playerid], true);

	NewSkinSelect[10][playerid] = CreatePlayerTextDraw(playerid,400.333312, 221.948089, "PreviewModel");
	PlayerTextDrawLetterSize(playerid,NewSkinSelect[10][playerid], 0.161333, 4.023707);
	PlayerTextDrawTextSize(playerid,NewSkinSelect[10][playerid], 61.666648, 69.274085);
	PlayerTextDrawAlignment(playerid,NewSkinSelect[10][playerid], 1);
	PlayerTextDrawColor(playerid,NewSkinSelect[10][playerid], -1);
	PlayerTextDrawSetShadow(playerid,NewSkinSelect[10][playerid], 0);
	PlayerTextDrawSetOutline(playerid,NewSkinSelect[10][playerid], 0);
	PlayerTextDrawBackgroundColor(playerid,NewSkinSelect[10][playerid], -707406934);
	PlayerTextDrawFont(playerid,NewSkinSelect[10][playerid], 5);
	PlayerTextDrawSetPreviewModel(playerid,NewSkinSelect[10][playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid,NewSkinSelect[10][playerid], 0.000000, 0.000000, 0.000000, 1.000000);
	PlayerTextDrawSetSelectable(playerid,NewSkinSelect[10][playerid], true);

	NewSkinSelect[11][playerid] = CreatePlayerTextDraw(playerid,465.333190, 221.703628, "PreviewModel");
	PlayerTextDrawLetterSize(playerid,NewSkinSelect[11][playerid], 0.159999, 4.048596);
	PlayerTextDrawTextSize(playerid,NewSkinSelect[11][playerid], 61.666648, 69.274085);
	PlayerTextDrawAlignment(playerid,NewSkinSelect[11][playerid], 1);
	PlayerTextDrawColor(playerid,NewSkinSelect[11][playerid], -1);
	PlayerTextDrawSetShadow(playerid,NewSkinSelect[11][playerid], 0);
	PlayerTextDrawSetOutline(playerid,NewSkinSelect[11][playerid], 0);
	PlayerTextDrawBackgroundColor(playerid,NewSkinSelect[11][playerid], -707406934);
	PlayerTextDrawFont(playerid,NewSkinSelect[11][playerid], 5);
	PlayerTextDrawSetPreviewModel(playerid,NewSkinSelect[11][playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid,NewSkinSelect[11][playerid], 0.000000, 0.000000, 0.000000, 1.000000);
	PlayerTextDrawSetSelectable(playerid,NewSkinSelect[11][playerid], true);

	NewSkinSelect[12][playerid] = CreatePlayerTextDraw(playerid,535.666625, 144.611114, "usebox");
	PlayerTextDrawLetterSize(playerid,NewSkinSelect[12][playerid], 0.000000, 16.829011);
	PlayerTextDrawTextSize(playerid,NewSkinSelect[12][playerid], 131.333328, 0.000000);
	PlayerTextDrawAlignment(playerid,NewSkinSelect[12][playerid], 1);
	PlayerTextDrawColor(playerid,NewSkinSelect[12][playerid], 0);
	PlayerTextDrawUseBox(playerid,NewSkinSelect[12][playerid], true);
	PlayerTextDrawBoxColor(playerid,NewSkinSelect[12][playerid], 102);
	PlayerTextDrawSetShadow(playerid,NewSkinSelect[12][playerid], 0);
	PlayerTextDrawSetOutline(playerid,NewSkinSelect[12][playerid], 0);
	PlayerTextDrawBackgroundColor(playerid,NewSkinSelect[12][playerid], 1438569727);
	PlayerTextDrawFont(playerid,NewSkinSelect[12][playerid], 0);
		
	
	
	dalnmenuplayer[playerid] = CreatePlayerTextDraw(playerid,365.000000, 123.000000, "~y~Щёлкните на любой из~n~прицепов.");PlayerTextDrawBackgroundColor(playerid,dalnmenuplayer[playerid], 255);PlayerTextDrawFont(playerid,dalnmenuplayer[playerid], 2);PlayerTextDrawLetterSize(playerid,dalnmenuplayer[playerid], 0.129999, 0.999999);PlayerTextDrawColor(playerid,dalnmenuplayer[playerid], -1);
	PlayerTextDrawSetOutline(playerid,dalnmenuplayer[playerid], 0);PlayerTextDrawSetProportional(playerid,dalnmenuplayer[playerid], 1);PlayerTextDrawSetShadow(playerid,dalnmenuplayer[playerid], 0);PlayerTextDrawSetSelectable(playerid,dalnmenuplayer[playerid], 0);
	
	menuPlayer[0][playerid] = CreatePlayerTextDraw(playerid,84.000000, 154.000000, "none");PlayerTextDrawBackgroundColor(playerid,menuPlayer[0][playerid], 255);PlayerTextDrawFont(playerid,menuPlayer[0][playerid], 2);PlayerTextDrawLetterSize(playerid,menuPlayer[0][playerid], 0.200000, 1.200000);PlayerTextDrawColor(playerid,menuPlayer[0][playerid], -1);
	PlayerTextDrawSetOutline(playerid,menuPlayer[0][playerid], 0);PlayerTextDrawSetProportional(playerid,menuPlayer[0][playerid], 1);PlayerTextDrawSetShadow(playerid,menuPlayer[0][playerid], 0);PlayerTextDrawSetSelectable(playerid,menuPlayer[0][playerid], 0);
	menuPlayer[1][playerid] = CreatePlayerTextDraw(playerid,256.000000, 154.000000, "none");PlayerTextDrawAlignment(playerid,menuPlayer[1][playerid], 3);PlayerTextDrawBackgroundColor(playerid,menuPlayer[1][playerid], 255);PlayerTextDrawFont(playerid,menuPlayer[1][playerid], 2);PlayerTextDrawLetterSize(playerid,menuPlayer[1][playerid], 0.200000, 1.200000);
	PlayerTextDrawColor(playerid,menuPlayer[1][playerid], -1);PlayerTextDrawSetOutline(playerid,menuPlayer[1][playerid], 0);PlayerTextDrawSetProportional(playerid,menuPlayer[1][playerid], 1);PlayerTextDrawSetShadow(playerid,menuPlayer[1][playerid], 0);PlayerTextDrawSetSelectable(playerid,menuPlayer[1][playerid], 0);
	menuPlayer[2][playerid] = CreatePlayerTextDraw(playerid,172.000000, 135.000000, "nick_names");PlayerTextDrawAlignment(playerid,menuPlayer[2][playerid], 2);PlayerTextDrawBackgroundColor(playerid,menuPlayer[2][playerid], 255);PlayerTextDrawFont(playerid,menuPlayer[2][playerid], 2);PlayerTextDrawLetterSize(playerid,menuPlayer[2][playerid], 0.230000, 1.399999);
	PlayerTextDrawColor(playerid,menuPlayer[2][playerid], -1);PlayerTextDrawSetOutline(playerid,menuPlayer[2][playerid], 0);PlayerTextDrawSetProportional(playerid,menuPlayer[2][playerid], 1);PlayerTextDrawSetShadow(playerid,menuPlayer[2][playerid], 0);PlayerTextDrawSetSelectable(playerid,menuPlayer[2][playerid], 0);PlayerTextDrawSetShadow(playerid,menuPlayer[2][playerid], 0);PlayerTextDrawSetSelectable(playerid,menuPlayer[2][playerid], 0);PlayerTextDrawSetSelectable(playerid,menuPlayer[2][playerid], 0);
	
	invSPlayer[playerid][0] = CreatePlayerTextDraw(playerid,433.000000, 116.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][0], 255);
    PlayerTextDrawFont(playerid,invSPlayer[playerid][0], 5);PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][0], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][0], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][0], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][0], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][0], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][0], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][0], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][0], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][0], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][0], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][0], 1);

    invSPlayer[playerid][1] = CreatePlayerTextDraw(playerid,466.000000, 116.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][1], 255);
    PlayerTextDrawFont(playerid,invSPlayer[playerid][1], 5);PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][1], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][1], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][1], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][1], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][1], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][1], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][1], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][1], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][1], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][1], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][1], 1);

    invSPlayer[playerid][2] = CreatePlayerTextDraw(playerid,498.799987, 116.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][2], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][2], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][2], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][2], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][2], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][2], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][2], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][2], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][2], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][2], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][2], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][2], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][2], 1);

    invSPlayer[playerid][3] = CreatePlayerTextDraw(playerid,531.500000, 116.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][3], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][3], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][3], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][3], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][3], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][3], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][3], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][3], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][3], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][3], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][3], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][3], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][3], 1);

    invSPlayer[playerid][4] = CreatePlayerTextDraw(playerid,564.500000, 116.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][4], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][4], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][4], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][4], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][4], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][4], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][4], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][4], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][4], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][4], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][4], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][4], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][4], 1);

    invSPlayer[playerid][5] = CreatePlayerTextDraw(playerid,597.500000, 116.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][5], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][5], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][5], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][5], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][5], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][5], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][5], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][5], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][5], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][5], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][5], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][5], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][5], 1);

    invSPlayer[playerid][6] = CreatePlayerTextDraw(playerid,433.000000, 156.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][6], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][6], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][6], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][6], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][6], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][6], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][6], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][6], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][6], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][6], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][6], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][6], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][6], 1);

    invSPlayer[playerid][7] = CreatePlayerTextDraw(playerid,466.000000, 156.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][7], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][7], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][7], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][7], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][7], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][7], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][7], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][7], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][7], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][7], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][7], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][7], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][7], 1);

    invSPlayer[playerid][8] = CreatePlayerTextDraw(playerid,498.799987, 156.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][8], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][8], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][8], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][8], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][8], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][8], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][8], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][8], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][8], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][8], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][8], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][8], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][8], 1);

    invSPlayer[playerid][9] = CreatePlayerTextDraw(playerid,531.500000, 156.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][9], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][9], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][9], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][9], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][9], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][9], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][9], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][9], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][9], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][9], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][9], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][9], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][9], 1);

    invSPlayer[playerid][10] = CreatePlayerTextDraw(playerid,564.500000, 156.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][10], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][10], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][10], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][10], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][10], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][10], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][10], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][10], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][10], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][10], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][10], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][10], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][10], 1);

    invSPlayer[playerid][11] = CreatePlayerTextDraw(playerid,597.500000, 156.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][11], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][11], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][11], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][11], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][11], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][11], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][11], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][11], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][11], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][11], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][11], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][11], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][11], 1);

    invSPlayer[playerid][12] = CreatePlayerTextDraw(playerid,433.000000, 197.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][12], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][12], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][12], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][12], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][12], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][12], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][12], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][12], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][12], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][12], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][12], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][12], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][12], 1);

    invSPlayer[playerid][13] = CreatePlayerTextDraw(playerid,466.000000, 197.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][13], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][13], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][13], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][13], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][13], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][13], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][13], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][13], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][13], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][13], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][13], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][13], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][13], 1);

    invSPlayer[playerid][14] = CreatePlayerTextDraw(playerid,498.799987, 197.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][14], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][14], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][14], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][14], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][14], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][14], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][14], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][14], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][14], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][14], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][14], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][14], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][14], 1);

    invSPlayer[playerid][15] = CreatePlayerTextDraw(playerid,531.500000, 197.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][15], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][15], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][15], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][15], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][15], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][15], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][15], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][15], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][15], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][15], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][15], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][15], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][15], 1);

    invSPlayer[playerid][16] = CreatePlayerTextDraw(playerid,564.500000, 197.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][16], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][16], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][16], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][16], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][16], 0);PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][16], 1);
    PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][16], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][16], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][16], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][16], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][16], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][16], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][16], 1);

    invSPlayer[playerid][17] = CreatePlayerTextDraw(playerid,597.500000, 197.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][17], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][17], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][17], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][17], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][17], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][17], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][17], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][17], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][17], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][17], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][17], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][17], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][17], 1);

    invSPlayer[playerid][18] = CreatePlayerTextDraw(playerid,433.000000, 237.300003, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][18], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][18], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][18], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][18], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][18], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][18], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][18], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][18], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][18], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][18], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][18], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][18], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][18], 1);

    invSPlayer[playerid][19] = CreatePlayerTextDraw(playerid,466.000000, 237.300003, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][19], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][19], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][19], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][19], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][19], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][19], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][19], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][19], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][19], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][19], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][19], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][19], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][19], 1);

    invSPlayer[playerid][20] = CreatePlayerTextDraw(playerid,498.799987, 237.300003, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][20], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][20], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][20], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][20], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][20], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][20], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][20], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][20], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][20], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][20], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][20], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][20], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][20], 1);

    invSPlayer[playerid][21] = CreatePlayerTextDraw(playerid,531.500000, 237.300003, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][21], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][21], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][21], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][21], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][21], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][21], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][21], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][21], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][21], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][21], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][21], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][21], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][21], 1);

    invSPlayer[playerid][22] = CreatePlayerTextDraw(playerid,564.500000, 237.300003, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][22], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][22], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][22], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][22], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][22], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][22], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][22], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][22], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][22], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][22], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][22], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][22], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][22], 1);

    invSPlayer[playerid][23] = CreatePlayerTextDraw(playerid,597.500000, 237.300003, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][23], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][23], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][23], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][23], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][23], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][23], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][23], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][23], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][23], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][23], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][23], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][23], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][23], 1);

    invSPlayer[playerid][24] = CreatePlayerTextDraw(playerid,433.000000, 277.299987, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][24], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][24], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][24], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][24], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][24], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][24], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][24], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][24], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][24], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][24], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][24], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][24], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][24], 1);

    invSPlayer[playerid][25] = CreatePlayerTextDraw(playerid,466.000000, 277.299987, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][25], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][25], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][25], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][25], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][25], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][25], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][25], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][25], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][25], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][25], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][25], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][25], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][25], 1);

    invSPlayer[playerid][26] = CreatePlayerTextDraw(playerid,498.799987, 277.299987, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][26], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][26], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][26], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][26], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][26], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][26], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][26], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][26], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][26], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][26], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][26], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][26], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][26], 1);

    invSPlayer[playerid][27] = CreatePlayerTextDraw(playerid,531.500000, 277.299987, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][27], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][27], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][27], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][27], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][27], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][27], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][27], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][27], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][27], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][27], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][27], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][27], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][27], 1);

    invSPlayer[playerid][28] = CreatePlayerTextDraw(playerid,564.500000, 277.299987, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][28], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][28], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][28], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][28], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][28], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][28], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][28], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][28], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][28], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][28], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][28], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][28], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][28], 1);

    invSPlayer[playerid][29] = CreatePlayerTextDraw(playerid,597.500000, 277.299987, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][29], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][29], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][29], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][29], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][29], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][29], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][29], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][29], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][29], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][29], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][29], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][29], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][29], 1);

    invSPlayer[playerid][30] = CreatePlayerTextDraw(playerid,433.000000, 317.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][30], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][30], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][30], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][30], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][30], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][30], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][30], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][30], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][30], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][30], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][30], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][30], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][30], 1);

    invSPlayer[playerid][31] = CreatePlayerTextDraw(playerid,466.000000, 317.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][31], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][31], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][31], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][31], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][31], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][31], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][31], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][31], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][31], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][31], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][31], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][31], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][31], 1);

    invSPlayer[playerid][32] = CreatePlayerTextDraw(playerid,498.799987, 317.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][32], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][32], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][32], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][32], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][32], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][32], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][32], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][32], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][32], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][32], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][32], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][32], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][32], 1);

    invSPlayer[playerid][33] = CreatePlayerTextDraw(playerid,531.500000, 317.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][33], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][33], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][33], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][33], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][33], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][33], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][33], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][33], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][33], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][33], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][33], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][33], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][33], 1);

    invSPlayer[playerid][34] = CreatePlayerTextDraw(playerid,564.500000, 317.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][34], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][34], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][34], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][34], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][34], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][34], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][34], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][34], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][34], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][34], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][34], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][34], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][34], 1);

    invSPlayer[playerid][35] = CreatePlayerTextDraw(playerid,597.500000, 317.500000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][35], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][35], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][35], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][35], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][35], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][35], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][35], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][35], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][35], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][35], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][35], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][35], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][35], 1);

    invSPlayer[playerid][36] = CreatePlayerTextDraw(playerid,433.000000, 358.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][36], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][36], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][36], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][36], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][36], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][36], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][36], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][36], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][36], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][36], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][36], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][36], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][36], 1);

    invSPlayer[playerid][37] = CreatePlayerTextDraw(playerid,466.000000, 358.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][37], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][37], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][37], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][37], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][37], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][37], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][37], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][37], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][37], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][37], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][37], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][37], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][37], 1);

    invSPlayer[playerid][38] = CreatePlayerTextDraw(playerid,498.799987, 358.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][38], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][38], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][38], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][38], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][38], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][38], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][38], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][38], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][38], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][38], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][38], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][38], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][38], 1);

    invSPlayer[playerid][39] = CreatePlayerTextDraw(playerid,531.500000, 358.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][39], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][39], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][39], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][39], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][39], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][39], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][39], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][39], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][39], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][39], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][39], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][39], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][39], 1);

    invSPlayer[playerid][40] = CreatePlayerTextDraw(playerid,564.500000, 358.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][40], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][40], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][40], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][40], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][40], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][40], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][40], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][40], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][40], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][40], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][40], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][40], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][40], 1);

    invSPlayer[playerid][41] = CreatePlayerTextDraw(playerid,597.500000, 358.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][41], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][41], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][41], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][41], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][41], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][41], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][41], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][41], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][41], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][41], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][41], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][41], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][41], 1);

    invSPlayer[playerid][42] = CreatePlayerTextDraw(playerid,433.000000, 398.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][42], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][42], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][42], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][42], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][42], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][42], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][42], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][42], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][42], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][42], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][42], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][42], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][42], 1);

    invSPlayer[playerid][43] = CreatePlayerTextDraw(playerid,466.000000, 398.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][43], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][43], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][43], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][43], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][43], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][43], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][43], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][43], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][43], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][43], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][43], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][43], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][43], 1);

    invSPlayer[playerid][44] = CreatePlayerTextDraw(playerid,498.799987, 398.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][44], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][44], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][44], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][44], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][44], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][44], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][44], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][44], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][44], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][44], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][44], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][44], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][44], 1);

    invSPlayer[playerid][45] = CreatePlayerTextDraw(playerid,531.500000, 398.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][45], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][45], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][45], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][45], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][45], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][45], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][45], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][45], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][45], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][45], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][45], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][45], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][45], 1);

    invSPlayer[playerid][46] = CreatePlayerTextDraw(playerid,564.500000, 398.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][46], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][46], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][46], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][46], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][46], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][46], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][46], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][46], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][46], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][46], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][46], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][46], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][46], 1);

    invSPlayer[playerid][47] = CreatePlayerTextDraw(playerid,597.500000, 398.000000, "SlotLeft");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][47], 255);
    PlayerTextDrawFont(playerid,invSPlayer[playerid][47], 5);PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][47], 0.509998, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][47], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][47], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][47], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][47], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][47], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][47], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][47], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][47], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][47], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][47], 1);

    invSPlayer[playerid][48] = CreatePlayerTextDraw(playerid,221.000000, 114.000000, "HUDslot1");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][48], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][48], 5);PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][48], 0.549996, 1.000000);
    PlayerTextDrawColor(playerid,invSPlayer[playerid][48], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][48], 0);PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][48], 1);
    PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][48], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][48], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][48], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][48], 34.000000, 39.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][48], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][48], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][48], 1);

    invSPlayer[playerid][49] = CreatePlayerTextDraw(playerid,383.500000, 114.000000, "HUDslot2");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][49], 255);
    PlayerTextDrawFont(playerid,invSPlayer[playerid][49], 5);PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][49], 0.549996, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][49], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][49], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][49], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][49], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][49], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][49], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][49], 34.000000, 39.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][49], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][49], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][49], 1);

    invSPlayer[playerid][50] = CreatePlayerTextDraw(playerid,221.000000, 170.000000, "HUDslot3");
    PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][50], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][50], 5);PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][50], 0.549996, 1.000000);
    PlayerTextDrawColor(playerid,invSPlayer[playerid][50], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][50], 0);PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][50], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][50], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][50], 1);
    PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][50], 0);PlayerTextDrawTextSize(playerid,invSPlayer[playerid][50], 34.000000, 39.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][50], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][50], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][50], 1);

    invSPlayer[playerid][51] = CreatePlayerTextDraw(playerid,383.500000, 170.000000, "HUDslot4");
    PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][51], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][51], 5);PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][51], 0.549996, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][51], -1);
    PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][51], 0);PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][51], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][51], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][51], 1);
    PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][51], 0);PlayerTextDrawTextSize(playerid,invSPlayer[playerid][51], 34.000000, 39.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][51], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][51], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][51], 1);

    invSPlayer[playerid][52] = CreatePlayerTextDraw(playerid,221.000000, 227.000000, "HUDslot5");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][52], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][52], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][52], 0.549996, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][52], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][52], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][52], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][52], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][52], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][52], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][52], 34.000000, 39.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][52], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][52], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][52], 1);

    invSPlayer[playerid][53] = CreatePlayerTextDraw(playerid,383.500000, 227.000000, "HUDslot6");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][53], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][53], 5);
    PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][53], 0.549996, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][53], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][53], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][53], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][53], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][53], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][53], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][53], 34.000000, 39.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][53], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][53], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][53], 1);

    invSPlayer[playerid][54] = CreatePlayerTextDraw(playerid,221.000000, 283.000000, "HUDslot7");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][54], 255);
    PlayerTextDrawFont(playerid,invSPlayer[playerid][54], 5);PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][54], 0.549996, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][54], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][54], 0);
    PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][54], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][54], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][54], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][54], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][54], 34.000000, 39.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][54], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][54], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][54], 1);

    invSPlayer[playerid][55] = CreatePlayerTextDraw(playerid,383.500000, 283.000000, "HUDslot8");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][55], 255);
    PlayerTextDrawFont(playerid,invSPlayer[playerid][55], 5);PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][55], 0.549996, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][55], -1);
    PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][55], 0);PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][55], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][55], 1);PlayerTextDrawUseBox(playerid,invSPlayer[playerid][55], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][55], 0);
    PlayerTextDrawTextSize(playerid,invSPlayer[playerid][55], 34.000000, 39.000000);PlayerTextDrawSetPreviewModel(playerid, invSPlayer[playerid][55], 19464);PlayerTextDrawSetPreviewRot(playerid, invSPlayer[playerid][55], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][55], 1);

    invSPlayer[playerid][56] = CreatePlayerTextDraw(playerid,224.399993, 403.500000, "__");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][56], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][56], 1);PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][56], 0.500000, 1.199998);
    PlayerTextDrawColor(playerid,invSPlayer[playerid][56], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][56], 0);PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][56], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][56], 1);
    PlayerTextDrawUseBox(playerid,invSPlayer[playerid][56], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][56], -16777072);PlayerTextDrawTextSize(playerid,invSPlayer[playerid][56], 220.000000, -31.000000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][56], 0);

    invSPlayer[playerid][57] = CreatePlayerTextDraw(playerid,224.399993, 421.500000, "__");PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][57], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][57], 1);PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][57], 0.500000, 1.199998);
    PlayerTextDrawColor(playerid,invSPlayer[playerid][57], -1);PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][57], 0);PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][57], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][57], 1);
    PlayerTextDrawUseBox(playerid,invSPlayer[playerid][57], 1);PlayerTextDrawBoxColor(playerid,invSPlayer[playerid][57], -1953920624);PlayerTextDrawTextSize(playerid,invSPlayer[playerid][57], 220.000000, -31.000000);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][57], 0);

    invSPlayer[playerid][58] = CreatePlayerTextDraw(playerid,321.000000, 367.000000, "~y~Roberto_Morello~w~~n~0/999kg");PlayerTextDrawAlignment(playerid,invSPlayer[playerid][58], 2);
    PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][58], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][58], 2);PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][58], 0.200000, 1.300000);PlayerTextDrawColor(playerid,invSPlayer[playerid][58], -1);
    PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][58], 0);PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][58], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][58], 0);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][58], 0);

    invSPlayer[playerid][59] = CreatePlayerTextDraw(playerid,321.000000, 404.000000, "100%");PlayerTextDrawAlignment(playerid,invSPlayer[playerid][59], 2);
    PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][59], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][59], 2);PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][59], 0.250000, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][59], -1);
    PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][59], 0);PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][59], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][59], 0);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][59], 0);

    invSPlayer[playerid][60] = CreatePlayerTextDraw(playerid,321.000000, 422.000000, "100%");PlayerTextDrawAlignment(playerid,invSPlayer[playerid][60], 2);
    PlayerTextDrawBackgroundColor(playerid,invSPlayer[playerid][60], 255);PlayerTextDrawFont(playerid,invSPlayer[playerid][60], 2);PlayerTextDrawLetterSize(playerid,invSPlayer[playerid][60], 0.250000, 1.000000);PlayerTextDrawColor(playerid,invSPlayer[playerid][60], -1);
    PlayerTextDrawSetOutline(playerid,invSPlayer[playerid][60], 0);PlayerTextDrawSetProportional(playerid,invSPlayer[playerid][60], 1);PlayerTextDrawSetShadow(playerid,invSPlayer[playerid][60], 0);PlayerTextDrawSetSelectable(playerid,invSPlayer[playerid][60], 0);
	
	
	iconUse[0][playerid] = CreatePlayerTextDraw(playerid,85.000000, 119.000000, "_");PlayerTextDrawBackgroundColor(playerid,iconUse[0][playerid], 255);PlayerTextDrawFont(playerid,iconUse[0][playerid], 2);
	PlayerTextDrawLetterSize(playerid,iconUse[0][playerid], 0.500000, 5.999999);PlayerTextDrawColor(playerid,iconUse[0][playerid], -1);PlayerTextDrawSetOutline(playerid,iconUse[0][playerid], 0);
	PlayerTextDrawSetProportional(playerid,iconUse[0][playerid], 1);PlayerTextDrawSetShadow(playerid,iconUse[0][playerid], 1);PlayerTextDrawUseBox(playerid,iconUse[0][playerid], 1);PlayerTextDrawBoxColor(playerid,iconUse[0][playerid], 1438569568);
	PlayerTextDrawTextSize(playerid,iconUse[0][playerid], 132.000000, 57.000000);PlayerTextDrawSetPreviewModel(playerid, iconUse[0][playerid], 1272);PlayerTextDrawSetPreviewRot(playerid, iconUse[0][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,iconUse[0][playerid], 0);
	
	iconUse[1][playerid] = CreatePlayerTextDraw(playerid,85.000000, 119.000000, "_");PlayerTextDrawBackgroundColor(playerid,iconUse[1][playerid], -707406849);
	PlayerTextDrawFont(playerid,iconUse[1][playerid], 5);PlayerTextDrawLetterSize(playerid,iconUse[1][playerid], 0.500000, 1.000000);PlayerTextDrawColor(playerid,iconUse[1][playerid], -1);
	PlayerTextDrawSetOutline(playerid,iconUse[1][playerid], 0);PlayerTextDrawSetProportional(playerid,iconUse[1][playerid], 1);PlayerTextDrawSetShadow(playerid,iconUse[1][playerid], 1);
	PlayerTextDrawUseBox(playerid,iconUse[1][playerid], 1);PlayerTextDrawBoxColor(playerid,iconUse[1][playerid], 0);PlayerTextDrawTextSize(playerid,iconUse[1][playerid], 47.000000, 54.000000);
	PlayerTextDrawSetPreviewModel(playerid, iconUse[1][playerid], 1272);PlayerTextDrawSetPreviewRot(playerid, iconUse[1][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,iconUse[1][playerid], 0);

	iconUse[2][playerid] = CreatePlayerTextDraw(playerid,85.000000, 119.000000, "_");PlayerTextDrawBackgroundColor(playerid,iconUse[1][playerid], -707406849);
	PlayerTextDrawFont(playerid,iconUse[1][playerid], 5);PlayerTextDrawLetterSize(playerid,iconUse[1][playerid], 0.500000, 1.000000);PlayerTextDrawColor(playerid,iconUse[1][playerid], -1);
	PlayerTextDrawSetOutline(playerid,iconUse[1][playerid], 0);PlayerTextDrawSetProportional(playerid,iconUse[1][playerid], 1);PlayerTextDrawSetShadow(playerid,iconUse[1][playerid], 1);
	PlayerTextDrawUseBox(playerid,iconUse[1][playerid], 1);PlayerTextDrawBoxColor(playerid,iconUse[1][playerid], 0);PlayerTextDrawTextSize(playerid,iconUse[1][playerid], 47.000000, 54.000000);
	PlayerTextDrawSetPreviewModel(playerid, iconUse[1][playerid], 1314);PlayerTextDrawSetPreviewRot(playerid, iconUse[1][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,iconUse[1][playerid], 0);
	
	slotUse[0][playerid] = CreatePlayerTextDraw(playerid,10.000000, 178.500000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[0][playerid], 255);PlayerTextDrawFont(playerid,slotUse[0][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[0][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[0][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[0][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[0][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[0][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[0][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[0][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[0][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[0][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[0][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[0][playerid], 1);
	
	slotUse[1][playerid] = CreatePlayerTextDraw(playerid,43.000000, 178.500000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[1][playerid], 255);PlayerTextDrawFont(playerid,slotUse[1][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[1][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[1][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[1][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[1][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[1][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[1][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[1][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[1][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[1][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[1][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[1][playerid], 1);
	
	slotUse[2][playerid] = CreatePlayerTextDraw(playerid,75.799987, 178.500000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[2][playerid], 255);PlayerTextDrawFont(playerid,slotUse[2][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[2][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[2][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[2][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[2][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[2][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[2][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[2][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[2][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[2][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[2][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[2][playerid], 1);
	
	slotUse[3][playerid] = CreatePlayerTextDraw(playerid,108.500000, 178.500000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[3][playerid], 255);PlayerTextDrawFont(playerid,slotUse[3][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[3][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[3][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[3][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[3][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[3][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[3][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[3][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[3][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[3][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[3][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[3][playerid], 1);
	
	slotUse[4][playerid] = CreatePlayerTextDraw(playerid,141.400000, 178.500000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[4][playerid], 255);PlayerTextDrawFont(playerid,slotUse[4][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[4][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[4][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[4][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[4][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[4][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[4][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[4][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[4][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[4][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[4][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[4][playerid], 1);
	
	slotUse[5][playerid] = CreatePlayerTextDraw(playerid,174.000000, 178.500000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[5][playerid], 255);PlayerTextDrawFont(playerid,slotUse[5][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[5][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[5][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[5][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[5][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[5][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[5][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[5][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[5][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[5][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[5][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[5][playerid], 1);
	
	slotUse[6][playerid] = CreatePlayerTextDraw(playerid,10.000000, 218.500000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[6][playerid], 255);PlayerTextDrawFont(playerid,slotUse[6][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[6][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[6][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[6][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[6][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[6][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[6][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[6][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[6][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[6][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[6][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[6][playerid], 1);
	
	slotUse[7][playerid] = CreatePlayerTextDraw(playerid,43.000000, 218.500000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[7][playerid], 255);PlayerTextDrawFont(playerid,slotUse[7][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[7][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[7][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[7][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[7][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[7][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[7][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[7][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[7][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[7][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[7][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[7][playerid], 1);
	
	slotUse[8][playerid] = CreatePlayerTextDraw(playerid,75.799987, 218.500000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[8][playerid], 255);PlayerTextDrawFont(playerid,slotUse[8][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[8][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[8][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[8][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[8][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[8][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[8][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[8][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[8][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[8][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[8][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[8][playerid], 1);
	
	slotUse[9][playerid] = CreatePlayerTextDraw(playerid,108.500000, 218.500000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[9][playerid], 255);PlayerTextDrawFont(playerid,slotUse[9][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[9][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[9][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[9][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[9][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[9][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[9][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[9][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[9][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[9][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[9][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[9][playerid], 1);
	
	slotUse[10][playerid] = CreatePlayerTextDraw(playerid,141.400000, 218.500000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[10][playerid], 255);PlayerTextDrawFont(playerid,slotUse[10][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[10][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[10][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[10][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[10][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[10][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[10][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[10][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[10][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[10][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[10][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[10][playerid], 1);
	
	slotUse[11][playerid] = CreatePlayerTextDraw(playerid,174.000000, 218.500000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[11][playerid], 255);PlayerTextDrawFont(playerid,slotUse[11][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[11][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[11][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[11][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[11][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[11][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[11][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[11][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[11][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[11][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[11][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[11][playerid], 1);
	
	slotUse[12][playerid] = CreatePlayerTextDraw(playerid,10.000000, 258.000000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[12][playerid], 255);PlayerTextDrawFont(playerid,slotUse[12][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[12][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[12][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[12][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[12][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[12][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[12][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[12][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[12][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[12][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[12][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[12][playerid], 1);
	
	slotUse[13][playerid] = CreatePlayerTextDraw(playerid,43.000000, 258.000000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[13][playerid], 255);PlayerTextDrawFont(playerid,slotUse[13][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[13][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[13][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[13][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[13][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[13][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[13][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[13][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[13][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[13][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[13][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[13][playerid], 1);
	
	slotUse[14][playerid] = CreatePlayerTextDraw(playerid,75.799987, 258.000000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[14][playerid], 255);PlayerTextDrawFont(playerid,slotUse[14][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[14][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[14][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[14][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[14][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[14][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[14][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[14][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[14][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[14][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[14][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[14][playerid], 1);
	
	slotUse[15][playerid] = CreatePlayerTextDraw(playerid,108.500000, 258.000000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[15][playerid], 255);PlayerTextDrawFont(playerid,slotUse[15][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[15][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[15][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[15][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[15][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[15][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[15][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[15][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[15][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[15][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[15][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[15][playerid], 1);
	
	slotUse[16][playerid] = CreatePlayerTextDraw(playerid,141.400000, 258.000000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[16][playerid], 255);PlayerTextDrawFont(playerid,slotUse[16][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[16][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[16][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[16][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[16][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[16][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[16][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[16][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[16][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[16][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[16][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[16][playerid], 1);
	
	slotUse[17][playerid] = CreatePlayerTextDraw(playerid,174.000000, 258.000000, "slotuse");PlayerTextDrawBackgroundColor(playerid,slotUse[17][playerid], 255);PlayerTextDrawFont(playerid,slotUse[17][playerid], 5);
	PlayerTextDrawLetterSize(playerid,slotUse[17][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,slotUse[17][playerid], -1);PlayerTextDrawSetOutline(playerid,slotUse[17][playerid], 0);
	PlayerTextDrawSetProportional(playerid,slotUse[17][playerid], 1);PlayerTextDrawSetShadow(playerid,slotUse[17][playerid], 1);PlayerTextDrawUseBox(playerid,slotUse[17][playerid], 1);PlayerTextDrawBoxColor(playerid,slotUse[17][playerid], 0);
	PlayerTextDrawTextSize(playerid,slotUse[17][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, slotUse[17][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, slotUse[17][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,slotUse[17][playerid], 1);
	
	
	
	
	
	HungerProgres[playerid] = CreatePlayerTextDraw(playerid,549.500000, 60.000000, "____");PlayerTextDrawBackgroundColor(playerid,HungerProgres[playerid], 255);PlayerTextDrawFont(playerid,HungerProgres[playerid], 1);PlayerTextDrawLetterSize(playerid,HungerProgres[playerid], 0.490000, -0.000000);
	PlayerTextDrawColor(playerid,HungerProgres[playerid], -1);PlayerTextDrawSetOutline(playerid,HungerProgres[playerid], 0);PlayerTextDrawSetProportional(playerid,HungerProgres[playerid], 1);PlayerTextDrawSetShadow(playerid,HungerProgres[playerid], 1);
	PlayerTextDrawUseBox(playerid,HungerProgres[playerid], 1);PlayerTextDrawBoxColor(playerid,HungerProgres[playerid], 0x559cd4AA);PlayerTextDrawTextSize(playerid,HungerProgres[playerid], 604.000000, 40.000000);PlayerTextDrawSetSelectable(playerid,HungerProgres[playerid], 0);
	
	//
	
	buyingShopItems[0][playerid] = CreatePlayerTextDraw(playerid,13.000000, 120.000000, "item");PlayerTextDrawBackgroundColor(playerid,buyingShopItems[0][playerid], -707406849);PlayerTextDrawFont(playerid,buyingShopItems[0][playerid], 5);
	PlayerTextDrawLetterSize(playerid,buyingShopItems[0][playerid], 0.500000, 0.699999);PlayerTextDrawColor(playerid,buyingShopItems[0][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopItems[0][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopItems[0][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopItems[0][playerid], 1);PlayerTextDrawUseBox(playerid,buyingShopItems[0][playerid], 1);PlayerTextDrawBoxColor(playerid,buyingShopItems[0][playerid], 0);
	PlayerTextDrawTextSize(playerid,buyingShopItems[0][playerid], 26.000000, 31.000000);PlayerTextDrawSetPreviewModel(playerid, buyingShopItems[0][playerid], 0);PlayerTextDrawSetPreviewRot(playerid, buyingShopItems[0][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,buyingShopItems[0][playerid], 1);
	buyingShopItems[1][playerid] = CreatePlayerTextDraw(playerid,13.000000, 160.000000, "item");PlayerTextDrawBackgroundColor(playerid,buyingShopItems[1][playerid], -707406849);PlayerTextDrawFont(playerid,buyingShopItems[1][playerid], 5);PlayerTextDrawLetterSize(playerid,buyingShopItems[1][playerid], 0.500000, 0.699999);
	PlayerTextDrawColor(playerid,buyingShopItems[1][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopItems[1][playerid], 0);PlayerTextDrawSetProportional(playerid,buyingShopItems[1][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopItems[1][playerid], 1);PlayerTextDrawUseBox(playerid,buyingShopItems[1][playerid], 1);
	PlayerTextDrawBoxColor(playerid,buyingShopItems[1][playerid], 0);PlayerTextDrawTextSize(playerid,buyingShopItems[1][playerid], 26.000000, 30.000000);PlayerTextDrawSetPreviewModel(playerid, buyingShopItems[1][playerid], 0);PlayerTextDrawSetPreviewRot(playerid, buyingShopItems[1][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,buyingShopItems[1][playerid], 1);
	buyingShopItems[2][playerid] = CreatePlayerTextDraw(playerid,13.000000, 200.000000, "item");PlayerTextDrawBackgroundColor(playerid,buyingShopItems[2][playerid], -707406849);PlayerTextDrawFont(playerid,buyingShopItems[2][playerid], 5);PlayerTextDrawLetterSize(playerid,buyingShopItems[2][playerid], 0.500000, 0.699999);PlayerTextDrawColor(playerid,buyingShopItems[2][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopItems[2][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopItems[2][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopItems[2][playerid], 1);PlayerTextDrawUseBox(playerid,buyingShopItems[2][playerid], 1);PlayerTextDrawBoxColor(playerid,buyingShopItems[2][playerid], 0);
	PlayerTextDrawTextSize(playerid,buyingShopItems[2][playerid], 26.000000, 30.000000);PlayerTextDrawSetPreviewModel(playerid, buyingShopItems[2][playerid], 0);PlayerTextDrawSetPreviewRot(playerid, buyingShopItems[2][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,buyingShopItems[2][playerid], 1);
	buyingShopItems[3][playerid] = CreatePlayerTextDraw(playerid,13.000000, 241.000000, "item");PlayerTextDrawBackgroundColor(playerid,buyingShopItems[3][playerid], -707406849);PlayerTextDrawFont(playerid,buyingShopItems[3][playerid], 5);PlayerTextDrawLetterSize(playerid,buyingShopItems[3][playerid], 0.500000, 0.699999);
	PlayerTextDrawColor(playerid,buyingShopItems[3][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopItems[3][playerid], 0);PlayerTextDrawSetProportional(playerid,buyingShopItems[3][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopItems[3][playerid], 1);PlayerTextDrawUseBox(playerid,buyingShopItems[3][playerid], 1);
	PlayerTextDrawBoxColor(playerid,buyingShopItems[3][playerid], 0);PlayerTextDrawTextSize(playerid,buyingShopItems[3][playerid], 26.000000, 30.000000);PlayerTextDrawSetPreviewModel(playerid, buyingShopItems[3][playerid], 0);PlayerTextDrawSetPreviewRot(playerid, buyingShopItems[3][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,buyingShopItems[3][playerid], 1);
	buyingShopItems[4][playerid] = CreatePlayerTextDraw(playerid,13.000000, 281.000000, "item");PlayerTextDrawBackgroundColor(playerid,buyingShopItems[4][playerid], -707406849);PlayerTextDrawFont(playerid,buyingShopItems[4][playerid], 5);PlayerTextDrawLetterSize(playerid,buyingShopItems[4][playerid], 0.500000, 0.699999);PlayerTextDrawColor(playerid,buyingShopItems[4][playerid], -1);
	PlayerTextDrawSetOutline(playerid,buyingShopItems[4][playerid], 0);PlayerTextDrawSetProportional(playerid,buyingShopItems[4][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopItems[4][playerid], 1);PlayerTextDrawUseBox(playerid,buyingShopItems[4][playerid], 1);
	PlayerTextDrawBoxColor(playerid,buyingShopItems[4][playerid], 0);PlayerTextDrawTextSize(playerid,buyingShopItems[4][playerid], 26.000000, 30.000000);PlayerTextDrawSetPreviewModel(playerid, buyingShopItems[4][playerid], 0);PlayerTextDrawSetPreviewRot(playerid, buyingShopItems[4][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,buyingShopItems[4][playerid], 1);
	buyingShopItems[5][playerid] = CreatePlayerTextDraw(playerid,13.000000, 321.000000, "item");PlayerTextDrawBackgroundColor(playerid,buyingShopItems[5][playerid], -707406849);PlayerTextDrawFont(playerid,buyingShopItems[5][playerid], 5);PlayerTextDrawLetterSize(playerid,buyingShopItems[5][playerid], 0.500000, 0.699999);PlayerTextDrawColor(playerid,buyingShopItems[5][playerid], -1);
	PlayerTextDrawSetOutline(playerid,buyingShopItems[5][playerid], 0);PlayerTextDrawSetProportional(playerid,buyingShopItems[5][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopItems[5][playerid], 1);PlayerTextDrawUseBox(playerid,buyingShopItems[5][playerid], 1);PlayerTextDrawBoxColor(playerid,buyingShopItems[5][playerid], 0);
	PlayerTextDrawTextSize(playerid,buyingShopItems[5][playerid], 26.000000, 30.000000);PlayerTextDrawSetPreviewModel(playerid, buyingShopItems[5][playerid], 0);PlayerTextDrawSetPreviewRot(playerid, buyingShopItems[5][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,buyingShopItems[5][playerid], 1);
	buyingShopItems[6][playerid] = CreatePlayerTextDraw(playerid,13.000000, 361.000000, "item");PlayerTextDrawBackgroundColor(playerid,buyingShopItems[6][playerid], -707406849);PlayerTextDrawFont(playerid,buyingShopItems[6][playerid], 5);PlayerTextDrawLetterSize(playerid,buyingShopItems[6][playerid], 0.500000, 0.699999);PlayerTextDrawColor(playerid,buyingShopItems[6][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopItems[6][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopItems[6][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopItems[6][playerid], 1);PlayerTextDrawUseBox(playerid,buyingShopItems[6][playerid], 1);PlayerTextDrawBoxColor(playerid,buyingShopItems[6][playerid], 0);
	PlayerTextDrawTextSize(playerid,buyingShopItems[6][playerid], 26.000000, 30.000000);PlayerTextDrawSetPreviewModel(playerid, buyingShopItems[6][playerid], 0);PlayerTextDrawSetPreviewRot(playerid, buyingShopItems[6][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,buyingShopItems[6][playerid], 1);
	buyingShopItems[7][playerid] = CreatePlayerTextDraw(playerid,13.000000, 401.000000, "item");PlayerTextDrawBackgroundColor(playerid,buyingShopItems[7][playerid], -707406849);PlayerTextDrawFont(playerid,buyingShopItems[7][playerid], 5);PlayerTextDrawLetterSize(playerid,buyingShopItems[7][playerid], 0.500000, 0.699999);PlayerTextDrawColor(playerid,buyingShopItems[7][playerid], -1);
	PlayerTextDrawSetOutline(playerid,buyingShopItems[7][playerid], 0);PlayerTextDrawSetProportional(playerid,buyingShopItems[7][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopItems[7][playerid], 1);PlayerTextDrawUseBox(playerid,buyingShopItems[7][playerid], 1);PlayerTextDrawBoxColor(playerid,buyingShopItems[7][playerid], 0);
	PlayerTextDrawTextSize(playerid,buyingShopItems[7][playerid], 26.000000, 30.000000);PlayerTextDrawSetPreviewModel(playerid, buyingShopItems[7][playerid], 0);PlayerTextDrawSetPreviewRot(playerid, buyingShopItems[7][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,buyingShopItems[7][playerid], 1);
	buyingShopItems[8][playerid] = CreatePlayerTextDraw(playerid,111.000000, 120.000000, "item");PlayerTextDrawBackgroundColor(playerid,buyingShopItems[8][playerid], -707406849);PlayerTextDrawFont(playerid,buyingShopItems[8][playerid], 5);PlayerTextDrawLetterSize(playerid,buyingShopItems[8][playerid], 0.500000, 0.699999);PlayerTextDrawColor(playerid,buyingShopItems[8][playerid], -1);
	PlayerTextDrawSetOutline(playerid,buyingShopItems[8][playerid], 0);PlayerTextDrawSetProportional(playerid,buyingShopItems[8][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopItems[8][playerid], 1);PlayerTextDrawUseBox(playerid,buyingShopItems[8][playerid], 1);PlayerTextDrawBoxColor(playerid,buyingShopItems[8][playerid], 0);
	PlayerTextDrawTextSize(playerid,buyingShopItems[8][playerid], 26.000000, 30.000000);PlayerTextDrawSetPreviewModel(playerid, buyingShopItems[8][playerid], 0);PlayerTextDrawSetPreviewRot(playerid, buyingShopItems[8][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,buyingShopItems[8][playerid], 1);
	buyingShopItems[9][playerid] = CreatePlayerTextDraw(playerid,111.000000, 160.000000, "item");PlayerTextDrawBackgroundColor(playerid,buyingShopItems[9][playerid], -707406849);PlayerTextDrawFont(playerid,buyingShopItems[9][playerid], 5);PlayerTextDrawLetterSize(playerid,buyingShopItems[9][playerid], 0.500000, 0.699999);PlayerTextDrawColor(playerid,buyingShopItems[9][playerid], -1);
	PlayerTextDrawSetOutline(playerid,buyingShopItems[9][playerid], 0);PlayerTextDrawSetProportional(playerid,buyingShopItems[9][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopItems[9][playerid], 1);PlayerTextDrawUseBox(playerid,buyingShopItems[9][playerid], 1);
	PlayerTextDrawBoxColor(playerid,buyingShopItems[9][playerid], 0);PlayerTextDrawTextSize(playerid,buyingShopItems[9][playerid], 26.000000, 30.000000);PlayerTextDrawSetPreviewModel(playerid, buyingShopItems[9][playerid], 0);PlayerTextDrawSetPreviewRot(playerid, buyingShopItems[9][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,buyingShopItems[9][playerid], 1);
	buyingShopItems[10][playerid] = CreatePlayerTextDraw(playerid,111.000000, 200.000000, "item");PlayerTextDrawBackgroundColor(playerid,buyingShopItems[10][playerid], -707406849);PlayerTextDrawFont(playerid,buyingShopItems[10][playerid], 5);PlayerTextDrawLetterSize(playerid,buyingShopItems[10][playerid], 0.500000, 0.699999);PlayerTextDrawColor(playerid,buyingShopItems[10][playerid], -1);
	PlayerTextDrawSetOutline(playerid,buyingShopItems[10][playerid], 0);PlayerTextDrawSetProportional(playerid,buyingShopItems[10][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopItems[10][playerid], 1);PlayerTextDrawUseBox(playerid,buyingShopItems[10][playerid], 1);
	PlayerTextDrawBoxColor(playerid,buyingShopItems[10][playerid], 0);PlayerTextDrawTextSize(playerid,buyingShopItems[10][playerid], 26.000000, 30.000000);PlayerTextDrawSetPreviewModel(playerid, buyingShopItems[10][playerid], 0);PlayerTextDrawSetPreviewRot(playerid, buyingShopItems[10][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,buyingShopItems[10][playerid], 1);
	buyingShopItems[11][playerid] = CreatePlayerTextDraw(playerid,111.000000, 241.000000, "item");PlayerTextDrawBackgroundColor(playerid,buyingShopItems[11][playerid], -707406849);PlayerTextDrawFont(playerid,buyingShopItems[11][playerid], 5);PlayerTextDrawLetterSize(playerid,buyingShopItems[11][playerid], 0.500000, 0.699999);PlayerTextDrawColor(playerid,buyingShopItems[11][playerid], -1);
	PlayerTextDrawSetOutline(playerid,buyingShopItems[11][playerid], 0);PlayerTextDrawSetProportional(playerid,buyingShopItems[11][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopItems[11][playerid], 1);PlayerTextDrawUseBox(playerid,buyingShopItems[11][playerid], 1);
	PlayerTextDrawBoxColor(playerid,buyingShopItems[11][playerid], 0);PlayerTextDrawTextSize(playerid,buyingShopItems[11][playerid], 26.000000, 30.000000);PlayerTextDrawSetPreviewModel(playerid, buyingShopItems[11][playerid], 0);PlayerTextDrawSetPreviewRot(playerid, buyingShopItems[11][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,buyingShopItems[11][playerid], 1);
	buyingShopItems[12][playerid] = CreatePlayerTextDraw(playerid,111.000000, 281.000000, "item");PlayerTextDrawBackgroundColor(playerid,buyingShopItems[12][playerid], -707406849);PlayerTextDrawFont(playerid,buyingShopItems[12][playerid], 5);PlayerTextDrawLetterSize(playerid,buyingShopItems[12][playerid], 0.500000, 0.699999);PlayerTextDrawColor(playerid,buyingShopItems[12][playerid], -1);
	PlayerTextDrawSetOutline(playerid,buyingShopItems[12][playerid], 0);PlayerTextDrawSetProportional(playerid,buyingShopItems[12][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopItems[12][playerid], 1);PlayerTextDrawUseBox(playerid,buyingShopItems[12][playerid], 1);
	PlayerTextDrawBoxColor(playerid,buyingShopItems[12][playerid], 0);PlayerTextDrawTextSize(playerid,buyingShopItems[12][playerid], 26.000000, 30.000000);PlayerTextDrawSetPreviewModel(playerid, buyingShopItems[12][playerid], 0);PlayerTextDrawSetPreviewRot(playerid, buyingShopItems[12][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,buyingShopItems[12][playerid], 1);
	buyingShopItems[13][playerid] = CreatePlayerTextDraw(playerid,111.000000, 321.000000, "item");PlayerTextDrawBackgroundColor(playerid,buyingShopItems[13][playerid], -707406849);PlayerTextDrawFont(playerid,buyingShopItems[13][playerid], 5);PlayerTextDrawLetterSize(playerid,buyingShopItems[13][playerid], 0.500000, 0.699999);PlayerTextDrawColor(playerid,buyingShopItems[13][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopItems[13][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopItems[13][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopItems[13][playerid], 1);PlayerTextDrawUseBox(playerid,buyingShopItems[13][playerid], 1);PlayerTextDrawBoxColor(playerid,buyingShopItems[13][playerid], 0);
	PlayerTextDrawTextSize(playerid,buyingShopItems[13][playerid], 26.000000, 30.000000);PlayerTextDrawSetPreviewModel(playerid, buyingShopItems[13][playerid], 0);PlayerTextDrawSetPreviewRot(playerid, buyingShopItems[13][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,buyingShopItems[13][playerid], 1);
	buyingShopItems[14][playerid] = CreatePlayerTextDraw(playerid,111.000000, 361.000000, "item");PlayerTextDrawBackgroundColor(playerid,buyingShopItems[14][playerid], -707406849);PlayerTextDrawFont(playerid,buyingShopItems[14][playerid], 5);PlayerTextDrawLetterSize(playerid,buyingShopItems[14][playerid], 0.500000, 0.699999);PlayerTextDrawColor(playerid,buyingShopItems[14][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopItems[14][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopItems[14][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopItems[14][playerid], 1);PlayerTextDrawUseBox(playerid,buyingShopItems[14][playerid], 1);PlayerTextDrawBoxColor(playerid,buyingShopItems[14][playerid], 0);
	PlayerTextDrawTextSize(playerid,buyingShopItems[14][playerid], 26.000000, 30.000000);PlayerTextDrawSetPreviewModel(playerid, buyingShopItems[14][playerid], 0);PlayerTextDrawSetPreviewRot(playerid, buyingShopItems[14][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,buyingShopItems[14][playerid], 1);
	buyingShopItems[15][playerid] = CreatePlayerTextDraw(playerid,111.000000, 401.000000, "item");PlayerTextDrawBackgroundColor(playerid,buyingShopItems[15][playerid], -707406849);PlayerTextDrawFont(playerid,buyingShopItems[15][playerid], 5);PlayerTextDrawLetterSize(playerid,buyingShopItems[15][playerid], 0.500000, 0.699999);PlayerTextDrawColor(playerid,buyingShopItems[15][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopItems[15][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopItems[15][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopItems[15][playerid], 1);PlayerTextDrawUseBox(playerid,buyingShopItems[15][playerid], 1);PlayerTextDrawBoxColor(playerid,buyingShopItems[15][playerid], 0);
	PlayerTextDrawTextSize(playerid,buyingShopItems[15][playerid], 26.000000, 30.000000);PlayerTextDrawSetPreviewModel(playerid, buyingShopItems[15][playerid], 0);PlayerTextDrawSetPreviewRot(playerid, buyingShopItems[15][playerid], 0.000000, 0.000000, 0.000000, 1.000000);PlayerTextDrawSetSelectable(playerid,buyingShopItems[15][playerid], 1);
	
	buyingShopInfo[0][playerid] = CreatePlayerTextDraw(playerid,41.000000, 119.000000, "none");PlayerTextDrawBackgroundColor(playerid,buyingShopInfo[0][playerid], 255);PlayerTextDrawFont(playerid,buyingShopInfo[0][playerid], 2);
	PlayerTextDrawLetterSize(playerid,buyingShopInfo[0][playerid], 0.130000, 0.899999);PlayerTextDrawColor(playerid,buyingShopInfo[0][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopInfo[0][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopInfo[0][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopInfo[0][playerid], 0);PlayerTextDrawSetSelectable(playerid,buyingShopInfo[0][playerid], 0);
	buyingShopInfo[1][playerid] = CreatePlayerTextDraw(playerid,41.000000, 159.000000, "none");PlayerTextDrawBackgroundColor(playerid,buyingShopInfo[1][playerid], 255);PlayerTextDrawFont(playerid,buyingShopInfo[1][playerid], 2);
	PlayerTextDrawLetterSize(playerid,buyingShopInfo[1][playerid], 0.130000, 0.899999);PlayerTextDrawColor(playerid,buyingShopInfo[1][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopInfo[1][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopInfo[1][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopInfo[1][playerid], 0);PlayerTextDrawSetSelectable(playerid,buyingShopInfo[1][playerid], 0);
	buyingShopInfo[2][playerid] = CreatePlayerTextDraw(playerid,41.000000, 198.000000, "none");PlayerTextDrawBackgroundColor(playerid,buyingShopInfo[2][playerid], 255);PlayerTextDrawFont(playerid,buyingShopInfo[2][playerid], 2);
	PlayerTextDrawLetterSize(playerid,buyingShopInfo[2][playerid], 0.130000, 0.899999);PlayerTextDrawColor(playerid,buyingShopInfo[2][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopInfo[2][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopInfo[2][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopInfo[2][playerid], 0);PlayerTextDrawSetSelectable(playerid,buyingShopInfo[2][playerid], 0);
	buyingShopInfo[3][playerid] = CreatePlayerTextDraw(playerid,41.000000, 239.000000, "none");PlayerTextDrawBackgroundColor(playerid,buyingShopInfo[3][playerid], 255);PlayerTextDrawFont(playerid,buyingShopInfo[3][playerid], 2);
	PlayerTextDrawLetterSize(playerid,buyingShopInfo[3][playerid], 0.130000, 0.899999);PlayerTextDrawColor(playerid,buyingShopInfo[3][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopInfo[3][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopInfo[3][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopInfo[3][playerid], 0);PlayerTextDrawSetSelectable(playerid,buyingShopInfo[3][playerid], 0);
	buyingShopInfo[4][playerid] = CreatePlayerTextDraw(playerid,41.000000, 279.000000, "none");PlayerTextDrawBackgroundColor(playerid,buyingShopInfo[4][playerid], 255);
	PlayerTextDrawFont(playerid,buyingShopInfo[4][playerid], 2);PlayerTextDrawLetterSize(playerid,buyingShopInfo[4][playerid], 0.130000, 0.899999);PlayerTextDrawColor(playerid,buyingShopInfo[4][playerid], -1);
	PlayerTextDrawSetOutline(playerid,buyingShopInfo[4][playerid], 0);PlayerTextDrawSetProportional(playerid,buyingShopInfo[4][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopInfo[4][playerid], 0);PlayerTextDrawSetSelectable(playerid,buyingShopInfo[4][playerid], 0);
	buyingShopInfo[5][playerid] = CreatePlayerTextDraw(playerid,41.000000, 319.000000, "none");PlayerTextDrawBackgroundColor(playerid,buyingShopInfo[5][playerid], 255);PlayerTextDrawFont(playerid,buyingShopInfo[5][playerid], 2);
	PlayerTextDrawLetterSize(playerid,buyingShopInfo[5][playerid], 0.130000, 0.899999);PlayerTextDrawColor(playerid,buyingShopInfo[5][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopInfo[5][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopInfo[5][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopInfo[5][playerid], 0);PlayerTextDrawSetSelectable(playerid,buyingShopInfo[5][playerid], 0);
	buyingShopInfo[6][playerid] = CreatePlayerTextDraw(playerid,41.000000, 359.000000, "none");PlayerTextDrawBackgroundColor(playerid,buyingShopInfo[6][playerid], 255);PlayerTextDrawFont(playerid,buyingShopInfo[6][playerid], 2);
	PlayerTextDrawLetterSize(playerid,buyingShopInfo[6][playerid], 0.130000, 0.899999);PlayerTextDrawColor(playerid,buyingShopInfo[6][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopInfo[6][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopInfo[6][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopInfo[6][playerid], 0);PlayerTextDrawSetSelectable(playerid,buyingShopInfo[6][playerid], 0);
	buyingShopInfo[7][playerid] = CreatePlayerTextDraw(playerid,41.000000, 399.000000, "none");PlayerTextDrawBackgroundColor(playerid,buyingShopInfo[7][playerid], 255);PlayerTextDrawFont(playerid,buyingShopInfo[7][playerid], 2);
	PlayerTextDrawLetterSize(playerid,buyingShopInfo[7][playerid], 0.130000, 0.899999);PlayerTextDrawColor(playerid,buyingShopInfo[7][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopInfo[7][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopInfo[7][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopInfo[7][playerid], 0);PlayerTextDrawSetSelectable(playerid,buyingShopInfo[7][playerid], 0);
	buyingShopInfo[8][playerid] = CreatePlayerTextDraw(playerid,139.000000, 118.000000, "none");PlayerTextDrawBackgroundColor(playerid,buyingShopInfo[8][playerid], 255);PlayerTextDrawFont(playerid,buyingShopInfo[8][playerid], 2);
	PlayerTextDrawLetterSize(playerid,buyingShopInfo[8][playerid], 0.130000, 0.899999);PlayerTextDrawColor(playerid,buyingShopInfo[8][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopInfo[8][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopInfo[8][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopInfo[8][playerid], 0);PlayerTextDrawSetSelectable(playerid,buyingShopInfo[8][playerid], 0);
	buyingShopInfo[9][playerid] = CreatePlayerTextDraw(playerid,139.000000, 158.000000, "none");PlayerTextDrawBackgroundColor(playerid,buyingShopInfo[9][playerid], 255);PlayerTextDrawFont(playerid,buyingShopInfo[9][playerid], 2);
	PlayerTextDrawLetterSize(playerid,buyingShopInfo[9][playerid], 0.130000, 0.899999);PlayerTextDrawColor(playerid,buyingShopInfo[9][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopInfo[9][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopInfo[9][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopInfo[9][playerid], 0);PlayerTextDrawSetSelectable(playerid,buyingShopInfo[9][playerid], 0);
	buyingShopInfo[10][playerid] = CreatePlayerTextDraw(playerid,139.000000, 198.000000, "none");PlayerTextDrawBackgroundColor(playerid,buyingShopInfo[10][playerid], 255);PlayerTextDrawFont(playerid,buyingShopInfo[10][playerid], 2);
	PlayerTextDrawLetterSize(playerid,buyingShopInfo[10][playerid], 0.130000, 0.899999);PlayerTextDrawColor(playerid,buyingShopInfo[10][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopInfo[10][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopInfo[10][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopInfo[10][playerid], 0);PlayerTextDrawSetSelectable(playerid,buyingShopInfo[10][playerid], 0);
	buyingShopInfo[11][playerid] = CreatePlayerTextDraw(playerid,139.000000, 239.000000, "none");PlayerTextDrawBackgroundColor(playerid,buyingShopInfo[11][playerid], 255);PlayerTextDrawFont(playerid,buyingShopInfo[11][playerid], 2);
	PlayerTextDrawLetterSize(playerid,buyingShopInfo[11][playerid], 0.130000, 0.899999);PlayerTextDrawColor(playerid,buyingShopInfo[11][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopInfo[11][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopInfo[11][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopInfo[11][playerid], 0);PlayerTextDrawSetSelectable(playerid,buyingShopInfo[11][playerid], 0);
	buyingShopInfo[12][playerid] = CreatePlayerTextDraw(playerid,139.000000, 279.000000, "none");PlayerTextDrawBackgroundColor(playerid,buyingShopInfo[12][playerid], 255);PlayerTextDrawFont(playerid,buyingShopInfo[12][playerid], 2);
	PlayerTextDrawLetterSize(playerid,buyingShopInfo[12][playerid], 0.130000, 0.899999);PlayerTextDrawColor(playerid,buyingShopInfo[12][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopInfo[12][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopInfo[12][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopInfo[12][playerid], 0);PlayerTextDrawSetSelectable(playerid,buyingShopInfo[12][playerid], 0);
	buyingShopInfo[13][playerid] = CreatePlayerTextDraw(playerid,139.000000, 319.000000, "none");PlayerTextDrawBackgroundColor(playerid,buyingShopInfo[13][playerid], 255);PlayerTextDrawFont(playerid,buyingShopInfo[13][playerid], 2);
	PlayerTextDrawLetterSize(playerid,buyingShopInfo[13][playerid], 0.130000, 0.899999);PlayerTextDrawColor(playerid,buyingShopInfo[13][playerid], -1);PlayerTextDrawSetOutline(playerid,buyingShopInfo[13][playerid], 0);
	PlayerTextDrawSetProportional(playerid,buyingShopInfo[13][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopInfo[13][playerid], 0);PlayerTextDrawSetSelectable(playerid,buyingShopInfo[13][playerid], 0);
	buyingShopInfo[14][playerid] = CreatePlayerTextDraw(playerid,139.000000, 359.000000, "none");PlayerTextDrawBackgroundColor(playerid,buyingShopInfo[14][playerid], 255);
	PlayerTextDrawFont(playerid,buyingShopInfo[14][playerid], 2);PlayerTextDrawLetterSize(playerid,buyingShopInfo[14][playerid], 0.130000, 0.899999);PlayerTextDrawColor(playerid,buyingShopInfo[14][playerid], -1);
	PlayerTextDrawSetOutline(playerid,buyingShopInfo[14][playerid], 0);PlayerTextDrawSetProportional(playerid,buyingShopInfo[14][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopInfo[14][playerid], 0);PlayerTextDrawSetSelectable(playerid,buyingShopInfo[14][playerid], 0);
	buyingShopInfo[15][playerid] = CreatePlayerTextDraw(playerid,139.000000, 399.000000, "none");PlayerTextDrawBackgroundColor(playerid,buyingShopInfo[15][playerid], 255);PlayerTextDrawFont(playerid,buyingShopInfo[15][playerid], 2);
	PlayerTextDrawLetterSize(playerid,buyingShopInfo[15][playerid], 0.130000, 0.899999);PlayerTextDrawColor(playerid,buyingShopInfo[15][playerid], -1);
	PlayerTextDrawSetOutline(playerid,buyingShopInfo[15][playerid], 0);PlayerTextDrawSetProportional(playerid,buyingShopInfo[15][playerid], 1);PlayerTextDrawSetShadow(playerid,buyingShopInfo[15][playerid], 0);PlayerTextDrawSetSelectable(playerid,buyingShopInfo[15][playerid], 0);
	
	infoIPlayer[playerid][0] = CreatePlayerTextDraw(playerid,223.000000, 116.500000, "_");
    infoIPlayer[playerid][1] = CreatePlayerTextDraw(playerid,386.000000, 116.500000, "_");
    infoIPlayer[playerid][2] = CreatePlayerTextDraw(playerid,223.000000, 172.500000, "_");
    infoIPlayer[playerid][3] = CreatePlayerTextDraw(playerid,386.000000, 172.500000, "_");
    infoIPlayer[playerid][4] = CreatePlayerTextDraw(playerid,223.000000, 229.500000, "_");
    infoIPlayer[playerid][5] = CreatePlayerTextDraw(playerid,386.000000, 229.500000, "_");
    infoIPlayer[playerid][6] = CreatePlayerTextDraw(playerid,223.000000, 285.500000, "_");
    infoIPlayer[playerid][7] = CreatePlayerTextDraw(playerid,386.000000, 285.500000, "_");
	
	for(new i; i != 8; i ++) {
		PlayerTextDrawBackgroundColor(playerid,infoIPlayer[playerid][i], 255);PlayerTextDrawFont(playerid,infoIPlayer[playerid][i], 2);PlayerTextDrawLetterSize(playerid,infoIPlayer[playerid][i], 0.500000, 3.799999);
		PlayerTextDrawColor(playerid,infoIPlayer[playerid][i], -1);PlayerTextDrawSetOutline(playerid,infoIPlayer[playerid][i], 0);PlayerTextDrawSetProportional(playerid,infoIPlayer[playerid][i], 1);
		PlayerTextDrawSetShadow(playerid,infoIPlayer[playerid][i], 1);PlayerTextDrawUseBox(playerid,infoIPlayer[playerid][i], 1);PlayerTextDrawBoxColor(playerid,infoIPlayer[playerid][i], 0x33AA3390);
	}
	
	PlayerTextDrawTextSize(playerid,infoIPlayer[playerid][0], 253.500000, 30.000000);
	PlayerTextDrawTextSize(playerid,infoIPlayer[playerid][2], 253.500000, 30.000000);
	PlayerTextDrawTextSize(playerid,infoIPlayer[playerid][4], 253.500000, 30.000000);
	PlayerTextDrawTextSize(playerid,infoIPlayer[playerid][6], 253.500000, 30.000000);
	
	PlayerTextDrawTextSize(playerid,infoIPlayer[playerid][1], 416.000000, 30.000000);
	PlayerTextDrawTextSize(playerid,infoIPlayer[playerid][3], 416.000000, 30.000000);
	PlayerTextDrawTextSize(playerid,infoIPlayer[playerid][5], 416.000000, 30.000000);
	PlayerTextDrawTextSize(playerid,infoIPlayer[playerid][7], 416.000000, 30.000000);
	
	furniturePrice[playerid] = CreatePlayerTextDraw(playerid,321.000000, 349.000000, "price");PlayerTextDrawAlignment(playerid,furniturePrice[playerid], 2);PlayerTextDrawBackgroundColor(playerid,furniturePrice[playerid], 255);
	PlayerTextDrawFont(playerid,furniturePrice[playerid], 2);PlayerTextDrawLetterSize(playerid,furniturePrice[playerid], 0.290000, 2.000000);PlayerTextDrawColor(playerid,furniturePrice[playerid], -1);
	PlayerTextDrawSetOutline(playerid,furniturePrice[playerid], 0);PlayerTextDrawSetProportional(playerid,furniturePrice[playerid], 1);PlayerTextDrawSetShadow(playerid,furniturePrice[playerid], 0);PlayerTextDrawSetSelectable(playerid,furniturePrice[playerid], 0);
	
	JobValueText[0][playerid] = CreatePlayerTextDraw(playerid, 54.333332, 424.770385, "Очки работы");
	PlayerTextDrawLetterSize(playerid, JobValueText[0][playerid], 0.156999, 1.537777);
	PlayerTextDrawAlignment(playerid, JobValueText[0][playerid], 1);
	PlayerTextDrawColor(playerid, JobValueText[0][playerid], 295035307);
	PlayerTextDrawSetShadow(playerid, JobValueText[0][playerid], 0);
	PlayerTextDrawSetOutline(playerid, JobValueText[0][playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, JobValueText[0][playerid], 51);
	PlayerTextDrawFont(playerid, JobValueText[0][playerid], 2);
	PlayerTextDrawSetProportional(playerid, JobValueText[0][playerid], 1);
	
	JobValueText[1][playerid] = CreatePlayerTextDraw(playerid, 116.294120, 426.249969, "_");
	PlayerTextDrawLetterSize(playerid, JobValueText[1][playerid], 0.221764, 1.483332);
	PlayerTextDrawTextSize(playerid, JobValueText[1][playerid], -23.058826, 19.250000);
	PlayerTextDrawAlignment(playerid, JobValueText[1][playerid], 2);
	PlayerTextDrawColor(playerid, JobValueText[1][playerid], 8847359);
	PlayerTextDrawUseBox(playerid, JobValueText[1][playerid], true);
	PlayerTextDrawBoxColor(playerid, JobValueText[1][playerid], 25);
	PlayerTextDrawSetShadow(playerid, JobValueText[1][playerid], 0);
	PlayerTextDrawSetOutline(playerid, JobValueText[1][playerid], 0);
	PlayerTextDrawBackgroundColor(playerid, JobValueText[1][playerid], 51);
	PlayerTextDrawFont(playerid, JobValueText[1][playerid], 2);
	PlayerTextDrawSetProportional(playerid, JobValueText[1][playerid], 1);
	
	RadioShow[0][playerid] = CreatePlayerTextDraw(playerid,549.176330, 104.416664, "Radio Info");
	PlayerTextDrawLetterSize(playerid, RadioShow[0][playerid], 0.319176, 1.436665);
	PlayerTextDrawTextSize(playerid, RadioShow[0][playerid], 6.117647, 91.583320);
	PlayerTextDrawAlignment(playerid, RadioShow[0][playerid], 2);
	PlayerTextDrawColor(playerid, RadioShow[0][playerid], -103346574);
	PlayerTextDrawSetShadow(playerid, RadioShow[0][playerid], 0);
	PlayerTextDrawSetOutline(playerid, RadioShow[0][playerid], 0);
	PlayerTextDrawBackgroundColor(playerid, RadioShow[0][playerid], 51);
	PlayerTextDrawFont(playerid, RadioShow[0][playerid], 3);
	PlayerTextDrawSetProportional(playerid, RadioShow[0][playerid], 1);

	RadioShow[1][playerid] = CreatePlayerTextDraw(playerid,516.235107, 118.999992, "CHANNEL:~n~SLOT:");
	PlayerTextDrawLetterSize(playerid,RadioShow[1][playerid], 0.236352, 1.290833);
	PlayerTextDrawAlignment(playerid,RadioShow[1][playerid], 1);
	PlayerTextDrawColor(playerid,RadioShow[1][playerid], -136);
	PlayerTextDrawSetShadow(playerid,RadioShow[1][playerid], 0);
	PlayerTextDrawSetOutline(playerid,RadioShow[1][playerid], 0);
	PlayerTextDrawBackgroundColor(playerid,RadioShow[1][playerid], 51);
	PlayerTextDrawFont(playerid,RadioShow[1][playerid], 1);
	PlayerTextDrawSetProportional(playerid,RadioShow[1][playerid], 1);

	RadioShow[2][playerid] = CreatePlayerTextDraw(playerid, 580.293945, 118.249969, "0~n~0");
	PlayerTextDrawLetterSize(playerid,RadioShow[2][playerid], 0.236352, 1.290833);
	PlayerTextDrawTextSize(playerid,RadioShow[2][playerid], 0.470588, 9.333333);
	PlayerTextDrawAlignment(playerid,RadioShow[2][playerid], 2);
	PlayerTextDrawColor(playerid,RadioShow[2][playerid], -150);
	PlayerTextDrawSetShadow(playerid,RadioShow[2][playerid], 0);
	PlayerTextDrawSetOutline(playerid,RadioShow[2][playerid], 0);
	PlayerTextDrawBackgroundColor(playerid,RadioShow[2][playerid], 51);
	PlayerTextDrawFont(playerid,RadioShow[2][playerid], 1);
	PlayerTextDrawSetProportional(playerid,RadioShow[2][playerid], 1);
	
	Warehouse[0][playerid] = CreatePlayerTextDraw(playerid,10.000000, 178.500000, "slotuse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[0][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[0][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[0][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[0][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[0][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[0][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[0][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[0][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[0][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[0][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[0][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[0][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[0][playerid], 1);
	
	Warehouse[1][playerid] = CreatePlayerTextDraw(playerid,43.000000, 178.500000, "slotuse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[1][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[1][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[1][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[1][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[1][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[1][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[1][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[1][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[1][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[1][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[1][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[1][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[1][playerid], 1);
	
	Warehouse[2][playerid] = CreatePlayerTextDraw(playerid,75.799987, 178.500000, "slotuse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[2][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[2][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[2][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[2][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[2][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[2][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[2][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[2][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[2][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[2][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[2][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[2][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[2][playerid], 1);
	
	Warehouse[3][playerid] = CreatePlayerTextDraw(playerid,108.500000, 178.500000, "slotuse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[3][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[3][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[3][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[3][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[3][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[3][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[3][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[3][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[3][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[3][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[3][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[3][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[3][playerid], 1);
	
	Warehouse[4][playerid] = CreatePlayerTextDraw(playerid,141.400000, 178.500000, "slotuse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[4][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[4][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[4][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[4][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[4][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[4][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[4][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[4][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[4][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[4][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[4][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[4][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[4][playerid], 1);
	
	Warehouse[5][playerid] = CreatePlayerTextDraw(playerid,174.000000, 178.500000, "slotuse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[5][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[5][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[5][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[5][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[5][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[5][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[5][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[5][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[5][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[5][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[5][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[5][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[5][playerid], 1);
	
	Warehouse[6][playerid] = CreatePlayerTextDraw(playerid,10.000000, 218.500000, "slotuse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[6][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[6][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[6][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[6][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[6][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[6][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[6][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[6][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[6][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[6][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[6][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[6][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[6][playerid], 1);
	
	Warehouse[7][playerid] = CreatePlayerTextDraw(playerid,43.000000, 218.500000, "slotuse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[7][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[7][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[7][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[7][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[7][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[7][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[7][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[7][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[7][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[7][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[7][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[7][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[7][playerid], 1);
	
	Warehouse[8][playerid] = CreatePlayerTextDraw(playerid,75.799987, 218.500000, "slotuse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[8][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[8][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[8][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[8][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[8][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[8][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[8][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[8][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[8][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[8][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[8][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[8][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[8][playerid], 1);
	
	Warehouse[9][playerid] = CreatePlayerTextDraw(playerid,108.500000, 218.500000, "slotuse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[9][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[9][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[9][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[9][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[9][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[9][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[9][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[9][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[9][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[9][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[9][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[9][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[9][playerid], 1);
	
	Warehouse[10][playerid] = CreatePlayerTextDraw(playerid,141.400000, 218.500000, "Warehouse");PlayerTextDrawBackgroundColor(playerid,Warehouse[10][playerid], 255);PlayerTextDrawFont(playerid,Warehouse[10][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[10][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,Warehouse[10][playerid], -1);PlayerTextDrawSetOutline(playerid,Warehouse[10][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[10][playerid], 1);PlayerTextDrawSetShadow(playerid,Warehouse[10][playerid], 1);PlayerTextDrawUseBox(playerid,Warehouse[10][playerid], 1);PlayerTextDrawBoxColor(playerid,Warehouse[10][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[10][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, Warehouse[10][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, Warehouse[10][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,Warehouse[10][playerid], 1);
	
	Warehouse[11][playerid] = CreatePlayerTextDraw(playerid,174.000000, 218.500000, "Warehouse");PlayerTextDrawBackgroundColor(playerid,Warehouse[11][playerid], 255);PlayerTextDrawFont(playerid,Warehouse[11][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[11][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,Warehouse[11][playerid], -1);PlayerTextDrawSetOutline(playerid,Warehouse[11][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[11][playerid], 1);PlayerTextDrawSetShadow(playerid,Warehouse[11][playerid], 1);PlayerTextDrawUseBox(playerid,Warehouse[11][playerid], 1);PlayerTextDrawBoxColor(playerid,Warehouse[11][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[11][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, Warehouse[11][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, Warehouse[11][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,Warehouse[11][playerid], 1);
	
	Warehouse[12][playerid] = CreatePlayerTextDraw(playerid,10.000000, 258.000000, "Warehouse");PlayerTextDrawBackgroundColor(playerid,Warehouse[12][playerid], 255);PlayerTextDrawFont(playerid,Warehouse[12][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[12][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,Warehouse[12][playerid], -1);PlayerTextDrawSetOutline(playerid,Warehouse[12][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[12][playerid], 1);PlayerTextDrawSetShadow(playerid,Warehouse[12][playerid], 1);PlayerTextDrawUseBox(playerid,Warehouse[12][playerid], 1);PlayerTextDrawBoxColor(playerid,Warehouse[12][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[12][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, Warehouse[12][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, Warehouse[12][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,Warehouse[12][playerid], 1);
	
	Warehouse[13][playerid] = CreatePlayerTextDraw(playerid,43.000000, 258.000000, "Warehouse");PlayerTextDrawBackgroundColor(playerid,Warehouse[13][playerid], 255);PlayerTextDrawFont(playerid,Warehouse[13][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[13][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,Warehouse[13][playerid], -1);PlayerTextDrawSetOutline(playerid,Warehouse[13][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[13][playerid], 1);PlayerTextDrawSetShadow(playerid,Warehouse[13][playerid], 1);PlayerTextDrawUseBox(playerid,Warehouse[13][playerid], 1);PlayerTextDrawBoxColor(playerid,Warehouse[13][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[13][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, Warehouse[13][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, Warehouse[13][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,Warehouse[13][playerid], 1);
	
	Warehouse[14][playerid] = CreatePlayerTextDraw(playerid,75.799987, 258.000000, "Warehouse");PlayerTextDrawBackgroundColor(playerid,Warehouse[14][playerid], 255);PlayerTextDrawFont(playerid,Warehouse[14][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[14][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,Warehouse[14][playerid], -1);PlayerTextDrawSetOutline(playerid,Warehouse[14][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[14][playerid], 1);PlayerTextDrawSetShadow(playerid,Warehouse[14][playerid], 1);PlayerTextDrawUseBox(playerid,Warehouse[14][playerid], 1);PlayerTextDrawBoxColor(playerid,Warehouse[14][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[14][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, Warehouse[14][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, Warehouse[14][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,Warehouse[14][playerid], 1);
	
	Warehouse[15][playerid] = CreatePlayerTextDraw(playerid,108.500000, 258.000000, "Warehouse");PlayerTextDrawBackgroundColor(playerid,Warehouse[15][playerid], 255);PlayerTextDrawFont(playerid,Warehouse[15][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[15][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,Warehouse[15][playerid], -1);PlayerTextDrawSetOutline(playerid,Warehouse[15][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[15][playerid], 1);PlayerTextDrawSetShadow(playerid,Warehouse[15][playerid], 1);PlayerTextDrawUseBox(playerid,Warehouse[15][playerid], 1);PlayerTextDrawBoxColor(playerid,Warehouse[15][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[15][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, Warehouse[15][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, Warehouse[15][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,Warehouse[15][playerid], 1);
	
	Warehouse[16][playerid] = CreatePlayerTextDraw(playerid,141.400000, 258.000000, "Warehouse");PlayerTextDrawBackgroundColor(playerid,Warehouse[16][playerid], 255);PlayerTextDrawFont(playerid,Warehouse[16][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[16][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,Warehouse[16][playerid], -1);PlayerTextDrawSetOutline(playerid,Warehouse[16][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[16][playerid], 1);PlayerTextDrawSetShadow(playerid,Warehouse[16][playerid], 1);PlayerTextDrawUseBox(playerid,Warehouse[16][playerid], 1);PlayerTextDrawBoxColor(playerid,Warehouse[16][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[16][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, Warehouse[16][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, Warehouse[16][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,Warehouse[16][playerid], 1);
	
	Warehouse[17][playerid] = CreatePlayerTextDraw(playerid,174.000000, 258.000000, "Warehouse");PlayerTextDrawBackgroundColor(playerid,Warehouse[17][playerid], 255);PlayerTextDrawFont(playerid,Warehouse[17][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[17][playerid], 0.509998, 1.000000);PlayerTextDrawColor(playerid,Warehouse[17][playerid], -1);PlayerTextDrawSetOutline(playerid,Warehouse[17][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[17][playerid], 1);PlayerTextDrawSetShadow(playerid,Warehouse[17][playerid], 1);PlayerTextDrawUseBox(playerid,Warehouse[17][playerid], 1);PlayerTextDrawBoxColor(playerid,Warehouse[17][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[17][playerid], 31.000000, 38.000000);PlayerTextDrawSetPreviewModel(playerid, Warehouse[17][playerid], 19464);PlayerTextDrawSetPreviewRot(playerid, Warehouse[17][playerid], 0.000000, 0.000000, 90.000000, 0.100000);PlayerTextDrawSetSelectable(playerid,Warehouse[17][playerid], 1);
	
	Warehouse[18][playerid] = CreatePlayerTextDraw(playerid,10.000000, 298.000000, "Warehouse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[18][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[18][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[18][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[18][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[18][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[18][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[18][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[18][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[18][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[18][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[18][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[18][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[18][playerid], 1);
	
	Warehouse[19][playerid] = CreatePlayerTextDraw(playerid,43.000000, 298.000000, "Warehouse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[19][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[19][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[19][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[19][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[19][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[19][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[19][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[19][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[19][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[19][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[19][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[19][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[19][playerid], 1);
	
	Warehouse[20][playerid] = CreatePlayerTextDraw(playerid,75.799987, 298.000000, "Warehouse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[20][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[20][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[20][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[20][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[20][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[20][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[20][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[20][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[20][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[20][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[20][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[20][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[20][playerid], 1);
	
	Warehouse[21][playerid] = CreatePlayerTextDraw(playerid,108.500000, 298.000000, "Warehouse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[21][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[21][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[21][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[21][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[21][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[21][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[21][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[21][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[21][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[21][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[21][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[21][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[21][playerid], 1);
	
	Warehouse[22][playerid] = CreatePlayerTextDraw(playerid,141.400000, 298.000000, "Warehouse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[22][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[22][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[22][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[22][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[22][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[22][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[22][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[22][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[22][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[22][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[22][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[22][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[22][playerid], 1);
	
	Warehouse[23][playerid] = CreatePlayerTextDraw(playerid,174.000000, 298.000000, "Warehouse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[23][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[23][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[23][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[23][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[23][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[23][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[23][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[23][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[23][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[23][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[23][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[23][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[23][playerid], 1);
	
	Warehouse[24][playerid] = CreatePlayerTextDraw(playerid,10.000000, 338.000000, "Warehouse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[24][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[24][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[24][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[24][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[24][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[24][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[24][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[24][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[24][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[24][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[24][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[24][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[24][playerid], 1);
	
	Warehouse[25][playerid] = CreatePlayerTextDraw(playerid,43.000000, 338.000000, "Warehouse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[25][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[25][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[25][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[25][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[25][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[25][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[25][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[25][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[25][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[25][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[25][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[25][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[25][playerid], 1);
	
	Warehouse[26][playerid] = CreatePlayerTextDraw(playerid,75.799987, 338.000000, "Warehouse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[26][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[26][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[26][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[26][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[26][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[26][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[26][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[26][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[26][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[26][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[26][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[26][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[26][playerid], 1);
	
	Warehouse[27][playerid] = CreatePlayerTextDraw(playerid,108.500000, 338.000000, "Warehouse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[27][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[27][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[27][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[27][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[27][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[27][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[27][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[27][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[27][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[27][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[27][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[27][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[27][playerid], 1);
	
	Warehouse[28][playerid] = CreatePlayerTextDraw(playerid,141.400000, 338.000000, "Warehouse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[28][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[28][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[28][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[28][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[28][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[28][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[28][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[28][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[28][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[28][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[28][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[28][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[28][playerid], 1);
	
	Warehouse[29][playerid] = CreatePlayerTextDraw(playerid,174.000000, 338.000000, "Warehouse");
	PlayerTextDrawBackgroundColor(playerid,Warehouse[29][playerid], 255);
	PlayerTextDrawFont(playerid,Warehouse[29][playerid], 5);
	PlayerTextDrawLetterSize(playerid,Warehouse[29][playerid], 0.509998, 1.000000);
	PlayerTextDrawColor(playerid,Warehouse[29][playerid], -1);
	PlayerTextDrawSetOutline(playerid,Warehouse[29][playerid], 0);
	PlayerTextDrawSetProportional(playerid,Warehouse[29][playerid], 1);
	PlayerTextDrawSetShadow(playerid,Warehouse[29][playerid], 1);
	PlayerTextDrawUseBox(playerid,Warehouse[29][playerid], 1);
	PlayerTextDrawBoxColor(playerid,Warehouse[29][playerid], 0);
	PlayerTextDrawTextSize(playerid,Warehouse[29][playerid], 31.000000, 38.000000);
	PlayerTextDrawSetPreviewModel(playerid, Warehouse[29][playerid], 19464);
	PlayerTextDrawSetPreviewRot(playerid, Warehouse[29][playerid], 0.000000, 0.000000, 90.000000, 0.100000);
	PlayerTextDrawSetSelectable(playerid,Warehouse[29][playerid], 1);