    fermcars[0] = CreateVehicle(532,-91.0908,19.0016,4.1017,66.7755,-1,-1,800);
	CreateVehicle(532,-94.9647,9.3151,4.0930,68.6420,-1,-1,800);
	CreateVehicle(532,-37.9381,60.0312,4.0942,344.0116,-1,-1,800);
	CreateVehicle(532,-35.7979,30.6017,4.0900,251.1563,-1,-1,800);
	CreateVehicle(531,-46.9425,93.4991,3.0787,160.0792,-1,-1,800);
	CreateVehicle(531,-43.4692,92.3867,3.0805,157.2212,-1,-1,800);
	CreateVehicle(531,-40.4582,91.3481,3.0819,159.4714,-1,-1,800);
	CreateVehicle(531,-37.4431,89.9878,3.0819,159.8694,-1,-1,800);
	CreateVehicle(610,-56.4135, 90.9243, 2.3695, -110.1001,-1,-1,800);
	CreateVehicle(610,-57.9004, 86.9105, 2.3695, -110.1001,-1,-1,800);
	CreateVehicle(610,-60.3985, 80.2338, 2.3695, -110.1001,-1,-1,800);
	CreateVehicle(610,-61.3490, 77.6532, 2.3695, -110.1001,-1,-1,800);
	CreateVehicle(478,-117.7714,-24.6899,3.1220,76.7403,-1,-1,800);
	CreateVehicle(478,-118.6667,-28.5680,3.1219,75.8310,-1,-1,800);
	CreateVehicle(478,-119.9122,-32.9480,3.1220,74.2573,-1,-1,800);
	fermcars[1] = CreateVehicle(478,-121.2525,-37.8990,3.1220,75.2779,-1,-1,800);
	
	
	ataxils[0] = CreateVehicle(420,1088.9409,-1226.6272,16.0,178.6907,6,6,800);
	CreateVehicle(420,1092.6241,-1226.7338,16.0,178.9950,6,6,800);
	CreateVehicle(420,1096.3928,-1226.6588,16.0,180.8550,6,6,800);
	CreateVehicle(420,1099.9102,-1226.6177,16.0,180.6205,6,6,800);
	CreateVehicle(420,1103.6561,-1226.5134,16.0,181.6215,6,6,800);
	CreateVehicle(420,1107.1093,-1226.4722,16.0,181.7509,6,6,800);
	CreateVehicle(420,1110.7136,-1226.4169,16.0,181.3345,6,6,800);
	CreateVehicle(438,1085.2361,-1249.6957,16.0,0.1132,6,6,800);
	CreateVehicle(438,1088.8696,-1249.6790,16.0,357.9916,6,6,800);
	CreateVehicle(438,1092.8350,-1249.7706,16.0,359.5025,6,6,800);
	CreateVehicle(438,1096.8307,-1249.7848,16.0,359.9141,6,6,800);
	CreateVehicle(438,1100.8572,-1249.9136,16.0,359.3941,6,6,800);
	CreateVehicle(438,1105.0309,-1249.9475,16.0,359.0828,6,6,800);
	ataxils[1] = CreateVehicle(438,1109.0743,-1249.9226,16.0,358.7137,6,6,800);
	
	
	buscars[0] = CreateVehicle(431,1706.3929,-1794.1786,13.6563,0.2937,0,4,800);
	CreateVehicle(431,1738.1858,-1799.5978,13.6297,358.2355,23,6,800);
	CreateVehicle(437,1779.9403,-1807.7632,13.6668,2.0635,16,10,800);
	CreateVehicle(437,1774.8795,-1807.6112,13.6688,0.6962,25,7,800);
	CreateVehicle(431,1711.6609,-1794.3020,13.6587,0.0550,24,20,800);
	CreateVehicle(431,1716.8049,-1794.2545,13.6414,0.1118,19,15,800);
	CreateVehicle(431,1721.6943,-1794.2360,13.6126,359.3346,21,7,800);
	CreateVehicle(431,1726.9880,-1794.2002,13.6045,359.4597,5,1,800);
	CreateVehicle(431,1732.3275,-1794.1959,13.6072,358.7247,0,12,800);
	CreateVehicle(437,1784.8361,-1807.4490,13.6707,2.2775,2,28,800);
	CreateVehicle(437,1790.0502,-1807.2104,13.6882,2.9639,10,15,800);
	CreateVehicle(437,1795.1191,-1807.1815,13.6759,1.4438,4,19,800);
	CreateVehicle(437,1800.1174,-1807.0767,13.6799,1.4345,21,14,800);
	buscars[1] = CreateVehicle(437,1805.0052,-1807.0031,13.6862,1.0648,28,6,800);
	
	
	dalncars[0] = CreateVehicle(498,2163.4971,-2313.3289,13.6160,314.2275,36,36,800);
	CreateVehicle(498,2166.8345,-2316.6970,13.6171,315.5631,13,120,800);
	CreateVehicle(403,2195.9158,-2189.7700,14.1581,225.1173,9,2,800);
	CreateVehicle(403,2192.7019,-2193.0813,14.1539,225.5576,21,29,800);
	CreateVehicle(403,2189.4063,-2196.3511,14.1558,225.8075,25,7,800);
	CreateVehicle(403,2186.0464,-2199.7227,14.1534,225.5355,3,21,800);
	CreateVehicle(514,2183.0442,-2204.1550,14.1359,225.7706,23,20,800);
	CreateVehicle(514,2180.0000,-2207.3325,14.1337,225.3732,13,1,800);
	CreateVehicle(514,2176.7334,-2210.6614,14.1353,224.7770,1,13,800);
	CreateVehicle(514,2173.5347,-2213.8218,14.1108,224.7037,16,21,800);
	CreateVehicle(515,2235.8130,-2245.9883,14.5792,45.0261,7,18,800);
	CreateVehicle(515,2228.1379,-2253.3562,14.5725,43.1278,2,15,800);
	CreateVehicle(515,2220.7446,-2260.6316,14.5755,44.0862,22,25,800);
	CreateVehicle(515,2213.2185,-2268.1628,14.5727,44.8789,7,22,800);
	CreateVehicle(498,2173.6616,-2266.3591,13.4380,225.9088,28,13,800);
	CreateVehicle(456,2168.0098,-2273.9182,13.5601,226.7312,24,9,800);
	CreateVehicle(499,2160.7366,-2280.4214,13.3709,225.8106,13,21,800);
	dalncars[1] = CreateVehicle(414,2153.7668,-2289.6487,13.4742,225.7004,21,1,800);
	
	new temp_car;
	lspdcars[0] = temp_car = CreateVehicle(426,1602.6948,-1671.2220,5.7206,89.3265,4,4, 86400); //
	vehicle_spawn[ lspdcars[0] ][vs_int] = 228, vehicle_spawn[ lspdcars[0] ][vs_world] = 3;
	LinkVehicleToInterior( lspdcars[0], 228 ), SetVehicleVirtualWorld( lspdcars[0], 3 );
	 
	temp_car = CreateVehicle(426,1602.5909,-1675.3561,5.6904,89.6514,40,40, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(426,1602.5878,-1679.8198,5.6879,89.1650,30,30, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(426,1602.5574,-1684.1842,5.6879,90.4051,20,20, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(426,1602.5935,-1688.0983,5.6887,90.6715,36,36, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(426,1602.6136,-1691.9575,5.6889,90.1940,11,11, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(426,1602.5704,-1696.2153,5.6863,88.5525,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(560,1602.8977,-1700.2799,5.7145,90.1941,36,36, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(560,1602.8562,-1704.5396,5.7149,89.2138,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(596,1595.4631,-1710.9384,5.6398,359.1656,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(596,1591.4911,-1710.8428,5.6503,0.1910,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(596,1587.7228,-1710.8228,5.6506,0.7928,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(596,1583.6970,-1710.8462,5.6496,1.6038,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(596,1578.5862,-1710.7622,5.6497,0.4457,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(596,1574.5228,-1710.6940,5.6521,359.2164,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(596,1570.3425,-1710.6296,5.6521,0.5475,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(596,1566.2524,-1710.4904,5.7063,0.0135,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(596,1562.6879,-1710.4764,5.7318,359.3711,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(596,1558.9669,-1710.2982,5.6521,0.1861,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(523,1545.5422,-1709.2726,5.4628,334.1666,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(523,1543.9901,-1708.4283,5.4640,333.9078,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(523,1542.3883,-1707.3505,5.4645,332.7109,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(523,1541.0797,-1706.0675,5.4613,316.1487,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(468,1539.8109,-1704.5736,5.4631,316.8804,1,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(468,1538.4829,-1703.2001,5.4634,315.7077,1,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(468,1537.5499,-1701.6383,5.4631,302.8736,1,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(522,1536.6379,-1699.6620,5.4633,301.5624,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(522,1535.9691,-1698.1671,5.4625,303.0033,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(522,1535.4128,-1696.6182,5.4602,302.2470,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(522,1534.9192,-1694.8268,5.4618,302.0253,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(599,1528.9194,-1687.8905,5.8971,268.5792,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(599,1529.0671,-1683.6240,5.9032,268.0929,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(415,1526.7543,-1644.0135,5.7047,181.0020,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(415,1530.8182,-1644.2078,5.7115,181.5903,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(415,1535.0276,-1644.2926,5.7127,179.2393,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(415,1538.9893,-1644.3768,5.7098,179.6666,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(597,1546.3123,-1650.9746,5.4218,89.1920,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(597,1546.1172,-1655.3090,5.4236,88.8695,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(597,1546.2606,-1659.2178,5.4222,90.2127,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(597,1546.3911,-1663.3922,5.4208,90.2803,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(597,1546.3817,-1668.1841,5.4239,89.8806,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(597,1546.3844,-1672.2246,5.4106,88.7191,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(596,1545.9440,-1676.2483,5.6917,89.5672,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(596,1546.0062,-1680.2892,5.6915,88.3228,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(596,1546.0007,-1684.7772,5.6917,89.7023,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(596,1546.0022,-1689.1632,5.6928,90.8183,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(424,1558.3485,-1693.4814,5.6767,180.3374,1,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(424,1562.1880,-1693.5668,5.6803,179.7835,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(424,1565.9727,-1693.6573,5.6708,180.1495,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(471,1571.8368,-1690.8500,5.3723,89.7089,1,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(471,1571.8636,-1693.1261,5.3904,89.2240,1,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(471,1571.8324,-1695.2534,5.3714,89.8571,1,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(471,1571.8358,-1697.7074,5.3724,90.8757,1,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(525,1585.1929,-1680.7725,6.0262,269.2860,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(525,1585.4507,-1676.2152,6.0306,271.1348,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(525,1585.5521,-1671.9478,6.0144,271.9917,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	 
	temp_car = CreateVehicle(525,1585.7679,-1668.0378,6.0167,269.8484,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 3;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 3 );
	//------------------ Гетто
	
	temp_car = CreateVehicle(482,1585.6781,-1667.7125,6.0198,268.7687,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );
	 
	temp_car = CreateVehicle(482,1585.5281,-1671.3903,6.0109,267.7208,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );
	 
	temp_car = CreateVehicle(482,1585.4904,-1675.3170,6.0163,269.3406,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );
	 
	temp_car = CreateVehicle(482,1585.2716,-1679.5311,6.0174,269.8594,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );
	 
	temp_car = CreateVehicle(426,1602.5762,-1671.9475,5.6873,87.5036,6,6, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(426,1602.5303,-1676.1494,5.6815,88.0579,44,44, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(426,1602.5138,-1680.0696,5.6859,89.1599,53,53, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(426,1602.5518,-1684.0306,5.6883,89.6018,3,3, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(426,1602.4972,-1687.8253,5.6776,86.3391,36,36, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(426,1602.5150,-1692.0813,5.6891,89.9075,1,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(426,1602.4989,-1696.1069,5.6884,90.2739,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(560,1602.8229,-1700.4170,5.7130,88.7527,36,36, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(560,1602.9325,-1704.4120,5.7142,88.7878,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(596,1595.2697,-1711.0776,5.6574,0.2872,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(596,1591.4028,-1710.9854,5.6589,359.3929,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(596,1587.5210,-1710.9144,5.6571,0.5979,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(596,1583.4302,-1710.9094,5.6571,1.0663,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(596,1578.4044,-1710.9591,5.6572,0.8608,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(596,1574.5748,-1710.9579,5.6586,358.8007,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(596,1570.6487,-1710.8843,5.6572,0.0033,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(596,1566.3141,-1710.8562,5.6910,0.5505,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(596,1562.8712,-1710.8749,5.6907,358.7613,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(596,1558.7554,-1710.7880,5.6573,359.9013,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(523,1545.9329,-1709.3306,5.4647,9.1882,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(523,1544.6133,-1709.0858,5.4622,9.6849,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(523,1543.2675,-1708.8724,5.4455,10.6779,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(523,1542.0211,-1707.9818,5.4605,7.0259,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(523,1540.0778,-1705.1028,5.4556,310.9596,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(523,1539.1809,-1704.0120,5.4612,310.2801,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(523,1538.1801,-1702.7490,5.4574,310.4323,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(523,1537.4031,-1701.1436,5.4541,311.3466,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(522,1535.9689,-1698.4130,5.5573,285.4010,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(522,1535.4657,-1696.7550,5.5575,287.4302,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(522,1535.1383,-1695.0640,5.5572,290.0769,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(522,1534.9124,-1693.1086,5.5575,294.2098,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(490,1529.3411,-1687.9637,5.8456,270.4045,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(490,1529.3143,-1683.3052,5.8456,270.2299,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(599,1526.6991,-1643.7687,5.9309,178.9796,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(599,1530.8153,-1643.7510,5.9312,178.6810,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(420,1534.6823,-1644.2002,5.5736,179.6379,6,6, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(420,1538.9232,-1644.2543,5.5736,179.4482,6,6, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(597,1546.3207,-1651.0652,5.4169,89.2627,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(597,1546.2509,-1655.2495,5.4168,88.8134,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(597,1546.0862,-1659.1881,5.4182,88.5915,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(597,1546.0912,-1663.3007,5.4168,89.2523,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(597,1545.9293,-1668.0299,5.4168,89.7495,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(597,1545.8369,-1672.0537,5.3684,87.5181,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(596,1545.5825,-1676.3236,5.6898,89.6674,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(596,1545.5510,-1680.2712,5.6898,89.5560,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(596,1545.4169,-1684.5277,5.6896,89.1657,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );

	temp_car = CreateVehicle(596,1545.3513,-1688.9188,5.6831,89.1797,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 2;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 2 );
	
	temp_car = CreateVehicle(497,2084.2214,-2149.8203,20.0991,46.2604,0,1, 86400 , 1); // Хеллипорт 
	temp_car = CreateVehicle(497,2100.1543,-2149.9546,20.0815,45.0553,0,1, 86400 , 1); // 
	temp_car = CreateVehicle(497,2101.5950,-2130.5957,20.0943,135.2576,0,1, 86400 , 1); // 
	temp_car = CreateVehicle(497,2076.4170,-2130.3159,20.1032,134.3672,0,1, 86400 , 1); // 
	temp_car = CreateVehicle(497,2049.5991,-2130.5474,20.0948,134.5204,0,1, 86400 , 1); // 

	temp_car = CreateVehicle(489,1586.4014,-1678.3949,5.9835,269.2853,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 4;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 4 );

	temp_car = CreateVehicle(489,1586.4205,-1673.2581,5.9808,270.2551,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 4;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 4 );

	temp_car = CreateVehicle(489,1586.4469,-1668.4515,5.9786,269.4784,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 4;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 4 );

	temp_car = CreateVehicle(601,1602.6704,-1671.3059,5.6517,91.0913,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 4;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 4 );

	temp_car = CreateVehicle(601,1602.6187,-1675.9663,5.6501,89.5505,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 4;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 4 );

	temp_car = CreateVehicle(528,1602.2057,-1680.3086,5.9484,89.1426,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 4;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 4 );

	temp_car = CreateVehicle(528,1602.1001,-1684.1462,5.9485,89.2458,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 4;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 4 );

	temp_car = CreateVehicle(528,1602.0607,-1688.2225,5.9488,89.5323,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 4;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 4 );

	temp_car = CreateVehicle(528,1602.0208,-1692.1461,5.9484,87.8034,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 4;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 4 );

	temp_car = CreateVehicle(427,1601.5417,-1696.1543,6.0902,89.7725,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 4;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 4 );

	temp_car = CreateVehicle(427,1601.5040,-1700.4457,6.0494,89.0530,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 4;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 4 );

	temp_car = CreateVehicle(427,1601.4839,-1704.7374,6.0910,88.5250,0,1, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 4;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 4 );

	temp_car = CreateVehicle(490,1595.8342,-1711.1423,5.8016,0.1062,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 4;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 4 );

	temp_car = CreateVehicle(490,1591.2596,-1711.4232,5.8018,0.1994,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 4;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 4 );

	temp_car = CreateVehicle(490,1587.3474,-1711.1443,5.8013,0.1971,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 4;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 4 );

	temp_car = CreateVehicle(490,1583.6570,-1711.0714,5.8032,1.1177,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 4;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 4 );

	temp_car = CreateVehicle(490,1578.3435,-1710.8884,5.8415,359.8242,0,0, 86400); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 4;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 4 );
	
	temp_car = CreateVehicle(427,1526.6316,-1645.2024,6.0915,179.6966,0,1, 86400, 1 ); // центр
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	temp_car = CreateVehicle(427,1530.8550,-1645.1997,6.0921,180.0284,0,1, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(579,1534.8608,-1643.7509,5.8925,180.0020,0,0, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(579,1538.8191,-1643.6259,5.8956,180.7362,0,0, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(599,1546.3904,-1651.0746,5.9007,90.4282,0,1, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(599,1546.3407,-1654.9952,5.8995,89.6346,0,1, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(560,1546.5604,-1659.0068,5.7142,89.3259,0,0, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(560,1546.5719,-1663.3008,5.7175,90.6214,0,0, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(560,1546.6725,-1667.9121,5.7143,90.2842,0,0, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(560,1546.7051,-1672.2271,5.7175,88.2426,0,0, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(415,1546.7950,-1676.2197,5.6627,89.4050,0,1, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(415,1546.7924,-1680.3075,5.6634,90.2798,0,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(415,1546.6876,-1684.3812,5.6626,90.2699,0,1, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(415,1546.8107,-1688.6049,5.6636,90.5142,0,1, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(490,1528.7053,-1683.6584,5.8425,271.6880,0,0, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(490,1528.6531,-1687.9523,5.8416,270.1638,0,0, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(521,1535.2021,-1694.6859,5.4617,283.4576,1,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(521,1535.4280,-1696.1821,5.4616,283.2185,1,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(521,1535.5920,-1697.6707,5.4601,284.0596,1,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(522,1536.4541,-1699.6154,5.4876,303.1778,1,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(522,1537.2180,-1700.8889,5.4859,305.6326,1,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(522,1537.9224,-1702.1942,5.4875,305.3792,1,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(523,1539.0554,-1703.8665,5.4627,317.8989,0,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(523,1540.1779,-1705.0483,5.4623,316.5936,0,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(523,1541.3296,-1706.2784,5.4623,317.9324,0,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(523,1542.4735,-1707.4524,5.4623,319.3215,0,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(523,1543.8689,-1708.3864,5.4649,334.4580,0,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(523,1545.2157,-1709.2007,5.4601,332.4388,0,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(416,1560.7384,-1693.7556,6.1041,268.7408,0,0, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(596,1558.9553,-1711.7748,5.6786,359.5384,0,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(596,1562.6217,-1711.7516,5.6928,359.9986,0,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(596,1566.4672,-1711.7604,5.6919,359.6126,0,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(596,1570.1333,-1711.7130,5.6928,0.0720,0,1, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(596,1574.3733,-1711.7750,5.6921,0.0735,0,1, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(596,1578.5536,-1711.7227,5.6887,359.9363,0,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(596,1583.1229,-1711.7294,5.7049,0.3886,0,1, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(597,1587.1932,-1711.9344,5.7614,0.0306,0,1, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(597,1591.2719,-1712.0366,5.7720,0.0188,0,1, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(597,1595.4575,-1711.9642,5.7630,359.0894,0,1, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(426,1602.6185,-1704.3575,5.6883,88.2249,0,0, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(426,1602.6659,-1700.2499,5.7024,90.8211,0,0, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(426,1602.6583,-1696.1010,5.6954,90.7233,0,0, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(426,1602.6135,-1692.1311,5.6839,89.2635,1,1, 86400, 1 ); // 
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 );
	temp_car = CreateVehicle(426,1602.5970,-1688.0088,5.6865,87.7318,36,36, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(426,1602.5536,-1683.9420,5.6865,89.8604,43,43, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(426,1602.6190,-1680.0515,5.6873,88.1299,53,53, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(482,1586.1187,-1679.7321,6.0180,268.8322,0,0, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(482,1586.1418,-1675.6617,6.0140,270.9746,0,0, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	temp_car = CreateVehicle(482,1586.2565,-1671.6042,6.0130,270.4300,0,0, 86400, 1 ); //
	vehicle_spawn[ temp_car ][vs_int] = 228, vehicle_spawn[ temp_car ][vs_world] = 1;
	LinkVehicleToInterior( temp_car, 228 ), SetVehicleVirtualWorld( temp_car, 1 ); 
	lspdcars[1] = CreateVehicle(482,1586.1504,-1668.0452,6.0135,270.2974,0,0, 86400, 1 ); //
	vehicle_spawn[ lspdcars[1] ][vs_int] = 228, vehicle_spawn[ lspdcars[1] ][vs_world] = 1;
	LinkVehicleToInterior( lspdcars[1], 228 ), SetVehicleVirtualWorld( lspdcars[1], 1 ); 
	vehicle_spawn[ lspdcars[1] ][vs_int] = 228, vehicle_spawn[ lspdcars[1] ][vs_world] = 1;
	
		
	sheriffandpolice[0] = CreateVehicle(430,-81.0938,-581.0895,-0.2714,225.2690,0,1,86400); // менты
	CreateVehicle(430,-85.8919,-585.7204,-0.2177,225.5717,0,1,86400); // менты
	CreateVehicle(430,2187.4399,-143.1183,-0.2644,179.7956,0,1,86400); // менты
	CreateVehicle(430,2187.4172,-158.0093,-0.2378,180.0500,0,1,86400); // менты

	CreateVehicle(430,2958.7949,-1511.2961,0.0281,259.6006,0,1,86400); // менты
	CreateVehicle(430,2959.6882,-1506.1586,0.2186,259.4765,0,1,86400); // менты

	CreateVehicle(430,2321.1345,-2385.0254,-0.3841,225.2085,0,1,86400); // менты
	CreateVehicle(430,2323.4963,-2398.5125,-0.3551,133.8147,0,1,86400); // менты
	CreateVehicle(430,2312.8354,-2408.8823,-0.4425,134.7355,0,1,86400); // менты
	CreateVehicle(430,406.7587,-1911.6602,-0.1518,182.8303,0,1,86400); // менты
	
	
	sheriffandpolice[1] = CreateVehicle(430,400.6509,-1929.7355,-0.2541,179.0276,0,1,86400); // менты
	
	
	
	//Аренда авто!
	carsalon[0][0] = CreateVehicle(409,2068.9934,-1905.0581,13.3481,180.5433,-1,-1,86400); // автосалон №1 (Гетто)
	CreateVehicle(491,2065.6067,-1904.0929,13.3027,180.7523,-1,-1,86400); // автосалон №2 (Гетто)
	CreateVehicle(517,2062.4419,-1903.9573,13.3998,179.6575,-1,-1,86400); // автосалон №1 (Гетто)
	CreateVehicle(527,2059.1287,-1904.1017,13.2602,179.9636,-1,-1,86400); // автосалон №1 (Гетто)
	CreateVehicle(535,2055.8535,-1904.2860,13.3044,179.8137,-1,-1,86400); // автосалон №1 (Гетто)
	CreateVehicle(442,2052.5396,-1904.6290,13.3793,180.4318,0,0,86400); // автосалон №1 (Гетто)
	CreateVehicle(551,2069.3420,-1918.8177,13.3486,359.4314,-1,-1,86400); // автосалон №1 (Гетто)
	CreateVehicle(555,2065.4202,-1919.4617,13.2315,0.7095,-1,-1,86400); // автосалон №1 (Гетто)
	CreateVehicle(462,2062.8521,-1919.7321,13.1428,0.5258,-1,-1,86400); // автосалон №1 (Гетто)
	carsalon[1][0] = CreateVehicle(462,2061.3862,-1919.5995,13.1359,2.4131,-1,-1,86400); // автосалон №1 (Гетто)
	
	carsalon[0][1] = CreateVehicle(409,357.7865,-1808.8521,4.3474,359.8474,-1,-1,86400); // автосалон №2 (ЛС)
	CreateVehicle(442,353.5530,-1808.9697,4.3669,0.1600,0,0,86400); // автосалон №2 (ЛС)
	CreateVehicle(405,350.2563,-1809.2024,4.4073,1.0039,-1,-1,86400); // автосалон №2 (ЛС)
	CreateVehicle(412,347.1209,-1808.8239,4.3766,0.5165,-1,-1,86400); // автосалон №2 (ЛС)
	CreateVehicle(419,343.8349,-1809.6835,4.3076,0.7701,-1,-1,86400); // автосалон №2 (ЛС)
	CreateVehicle(421,340.7006,-1809.4426,4.3933,359.5387,-1,-1,86400); // автосалон №2 (ЛС)
	CreateVehicle(436,337.3437,-1809.1251,4.2818,359.8626,-1,-1,86400); // автосалон №2 (ЛС)
	CreateVehicle(467,334.0156,-1809.0062,4.2366,0.4116,-1,-1,86400); // автосалон №2 (ЛС)
	CreateVehicle(462,330.9431,-1809.2056,4.0806,3.2513,-1,-1,86400); // автосалон №2 (ЛС)
	carsalon[1][1] = CreateVehicle(462,327.7980,-1809.2627,4.0707,359.3671,-1,-1,86400); // автосалон №2 (ЛС)
	
	carsalon[0][2] = CreateVehicle(487,1991.3146,-2310.2952,13.7671,287.4415,-1,-1,86400); // 487
	CreateVehicle(487,1990.4380,-2292.3022,13.7005,283.4764,-1,-1,86400); // 487 _2
	CreateVehicle(469,2022.8711,-2351.8904,13.5601,317.7521,-1,-1,86400); // 469_1
	CreateVehicle(469,2036.7469,-2352.4893,13.5585,317.2421,-1,-1,86400); // 469_2
	CreateVehicle(511,2112.6824,-2426.3640,14.9194,178.0761,-1,-1,86400); // 511
	CreateVehicle(519,2046.6617,-2419.4417,14.4673,217.4800,-1,-1,86400); // 519
	carsalon[1][2] = CreateVehicle(593,2082.6697,-2388.7476,14.0118,157.5542,-1,-1,86400); // 593
	
	carsalon[0][3] = CreateVehicle(484,2329.4492,-2511.6851,-0.0344,272.7447,-1,-1,86400); // аренда лодок (№4)
	CreateVehicle(484,2330.9832,-2564.3540,0.4872,269.4326,-1,-1,86400); // аренда лодок (№4)
	CreateVehicle(454,2301.5959,-2542.5813,0.3969,270.3586,-1,-1,86400); // аренда лодок (№4)
	CreateVehicle(454,2301.6089,-2533.3120,-0.1231,270.0898,-1,-1,86400); // аренда лодок (№4)
	CreateVehicle(493,2300.0398,-2525.7759,-0.0173,270.7432,-1,-1,86400); // аренда лодок (№4)
	CreateVehicle(473,2319.2241,-2523.7314,0.0402,271.1984,-1,-1,86400); // аренда лодок (№4)
	CreateVehicle(473,2327.7637,-2523.7012,-0.2283,268.9990,-1,-1,86400); // аренда лодок (№4)
	CreateVehicle(446,2300.4255,-2550.3015,-0.7884,270.1352,-1,-1,86400); // аренда лодок (№4)
	CreateVehicle(452,2319.1509,-2552.1868,-0.6980,271.9871,-1,-1,86400); // аренда лодок (№4)
	carsalon[1][3] = CreateVehicle(452,2332.4011,-2552.1497,-0.7836,271.2569,-1,-1,86400); // аренда лодок (№4)
	
	medicalcar[0] = CreateVehicle(426,1131.1194,-1347.2985,13.8806,180.0037,3,3,86400, 1); // premier(СИНИЙ) (id 426)
	CreateVehicle(426,1126.1263,-1347.2950,13.8646,179.8685,3,3,86400, 1); // premier(СИНИЙ)) (id 426)
	CreateVehicle(426,1120.9994,-1347.2993,13.8966,180.0028,3,3,86400, 1); // premier(СИНИЙ) (id 426)
	CreateVehicle(426,1115.8695,-1347.2994,13.8966,180.0014,3,3,86400, 1); // premier(СИНИЙ) (id 426)
	CreateVehicle(426,1110.7650,-1347.2920,13.8996,179.7476,3,3,86400, 1); // premier(СИНИЙ) (id 426)
	
	
	
	CreateVehicle(417,1163.4683,-1364.3446,26.6539,91.2702,1,1,86400); // AddVertolet
	CreateVehicle(497,1163.4222,-1375.6338,26.8043,91.1490,3,1,86400); // ChangeOldVert2
	CreateVehicle(497,1164.0881,-1351.5786,26.8033,91.1143,3,1,86400); // ChangeOldVert1
	CreateVehicle(416,1129.0625,-1365.4012,13.8399,356.8693,3,3,86400); // ChangeOldSkoraya1
	CreateVehicle(416,1118.0067,-1365.1011,13.8405,0.0022,3,3,86400); // ChangeOldSkoraya2
	CreateVehicle(416,1122.8453,-1365.1041,13.9150,359.8977,3,3,86400); // ChangeOldSkoraya3
	CreateVehicle(416,1179.2692,-1308.4353,13.9612,269.8967,3,3,86400); // ChangeOldSkoraya4
	CreateVehicle(416,1114.6708,-1326.0668,13.8488,181.3297,3,3,86400); // AddNewCar2
	CreateVehicle(416,1119.8315,-1326.0858,13.9097,179.6068,3,3,86400); // AddNewCar3
	medicalcar[1] = CreateVehicle(490,1124.2418,-1325.8207,13.8225,180.9033,3,3,86400); // ChangeRancher
	
	

	//Кары СНН от жустина!
	smicars[0] = CreateVehicle(488,1655.0829,-1636.8474,83.9916,270.2513,165,166,86400); // цвет 166,166 
	CreateVehicle(582,1670.5043,-1701.4390,20.5225,89.6013,3,1,86400); // цвет 3,1 
	CreateVehicle(582,1670.3993,-1705.4662,20.5201,88.9186,53,1,86400); // цвет 53,1 
	CreateVehicle(582,1670.4812,-1708.9965,20.5163,87.3903,234,1,86400); // цвет 234,1 
	CreateVehicle(582,1670.5084,-1713.0643,20.5147,87.6457,135,1,86400); // цвет 135,1 
	CreateVehicle(582,1670.4374,-1716.7062,20.5208,89.0697,1,1,86400); // цвет 1,1 
	CreateVehicle(582,1670.4391,-1720.4296,20.5958,89.9975,35,1,86400); // цвет 36,1 
	CreateVehicle(551,1670.8673,-1697.7754,20.2825,90.4731,53,53,86400); // цвет 53,53
	CreateVehicle(405,1656.0365,-1695.6454,20.3331,180.1796,53,53,86400); // цвет 53,53
	CreateVehicle(561,1661.7842,-1695.5817,20.2780,180.8864,53,53,86400); // цвет 53,53
	smicars[1] = CreateVehicle(437,1633.0613,-1684.7795,13.5842,181.7419,53,53,86400); // цвет 53,53
	
	comm[0] = CreateVehicle(421,2298.9778,-40.1919,26.2870,179.0415,1,1,86400);
	comm[1] = CreateVehicle(421,2288.3879,-45.1409,26.2894,180.2202,1,1,86400);